# cloudbuild/oli-api.yaml

substitutions:
  _AR_HOSTNAME: "us-central1-docker.pkg.dev"
  _AR_PROJECT_ID: "oli-staging-fdbba"
  _AR_REPOSITORY: "cloud-run-source-deploy"
  _SERVICE_NAME: "oli-api"
  _DEPLOY_REGION: "us-central1"
  _PLATFORM: "managed"

steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f", "services/api/Dockerfile",
        "-t", "${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}",
        "-t", "${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:latest",
        "."
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}"
      ]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: "gcloud"
    args:
      [
        "run", "services", "update", "${_SERVICE_NAME}",
        "--image", "${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}",
        "--region", "${_DEPLOY_REGION}",
        "--platform", "${_PLATFORM}",
        "--quiet"
      ]

images:
  - "${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}"
