/**
 * Hypertrophy Core v1 — Phase 6 expansion (+50 exercises, 50 → 100 total).
 * Imported into hypertrophyCoreV1.ts; SFR derived by defineIntelligence().
 */

import type { ExerciseIntelligenceV1 } from "./exerciseIntelligenceV1Types";

type IntelligenceSeed = Omit<ExerciseIntelligenceV1, "schemaVersion" | "exerciseId" | "stimulusToFatigueRatio">;

const EVIDENCE = "heuristic" as const;

/** Fifty additional catalog anchors covering regional gaps (verified in library). */
export const HYPERTROPHY_CORE_V1_PHASE6_SEEDS: Record<string, IntelligenceSeed> = {
  // Upper chest
  cable_incline_fly: {
    evidenceLevel: EVIDENCE,
    stimulus: { upperChest: 0.72, frontDelts: 0.14, midChest: 0.1, biceps: 0.04 },
    fatigue: 0.28,
    recoveryDemand: 0.24,
    jointStress: { shoulderStress: 0.4, elbowStress: 0.16, wristStress: 0.12, lumbarStress: 0.08 },
    skillRequirement: 0.28,
    mobilityRequirement: 0.32,
    stabilityRequirement: 0.3,
    loadedStretch: 0.68,
    hypertrophyPotential: 0.78,
    frequencySuitability: 0.84,
    progressionPotential: 0.68,
  },
  machine_incline_chest_press: {
    evidenceLevel: EVIDENCE,
    stimulus: { upperChest: 0.5, midChest: 0.18, triceps: 0.2, frontDelts: 0.12 },
    fatigue: 0.4,
    recoveryDemand: 0.34,
    jointStress: { shoulderStress: 0.38, elbowStress: 0.24, wristStress: 0.12, lumbarStress: 0.08 },
    skillRequirement: 0.2,
    mobilityRequirement: 0.26,
    stabilityRequirement: 0.22,
    loadedStretch: 0.42,
    hypertrophyPotential: 0.76,
    frequencySuitability: 0.84,
    progressionPotential: 0.74,
  },
  smith_machine_incline_bench: {
    evidenceLevel: EVIDENCE,
    stimulus: { upperChest: 0.46, triceps: 0.24, frontDelts: 0.2, midChest: 0.1 },
    fatigue: 0.52,
    recoveryDemand: 0.44,
    jointStress: { shoulderStress: 0.48, elbowStress: 0.28, wristStress: 0.18, lumbarStress: 0.14 },
    skillRequirement: 0.38,
    mobilityRequirement: 0.36,
    stabilityRequirement: 0.32,
    loadedStretch: 0.46,
    hypertrophyPotential: 0.82,
    frequencySuitability: 0.76,
    progressionPotential: 0.88,
  },
  cable_crossover_low_to_high: {
    evidenceLevel: EVIDENCE,
    stimulus: { upperChest: 0.68, frontDelts: 0.16, midChest: 0.1, biceps: 0.06 },
    fatigue: 0.26,
    recoveryDemand: 0.22,
    jointStress: { shoulderStress: 0.36, elbowStress: 0.14, wristStress: 0.1, lumbarStress: 0.08 },
    skillRequirement: 0.24,
    mobilityRequirement: 0.28,
    stabilityRequirement: 0.26,
    loadedStretch: 0.65,
    hypertrophyPotential: 0.76,
    frequencySuitability: 0.86,
    progressionPotential: 0.66,
  },
  // Lower chest
  dumbbell_decline_bench_press: {
    evidenceLevel: EVIDENCE,
    stimulus: { lowerChest: 0.48, triceps: 0.24, frontDelts: 0.16, midChest: 0.12 },
    fatigue: 0.54,
    recoveryDemand: 0.46,
    jointStress: { shoulderStress: 0.46, elbowStress: 0.28, wristStress: 0.2, lumbarStress: 0.14 },
    skillRequirement: 0.44,
    mobilityRequirement: 0.36,
    stabilityRequirement: 0.5,
    loadedStretch: 0.48,
    hypertrophyPotential: 0.82,
    frequencySuitability: 0.76,
    progressionPotential: 0.86,
  },
  cable_decline_fly: {
    evidenceLevel: EVIDENCE,
    stimulus: { lowerChest: 0.7, frontDelts: 0.14, midChest: 0.1, biceps: 0.06 },
    fatigue: 0.27,
    recoveryDemand: 0.22,
    jointStress: { shoulderStress: 0.38, elbowStress: 0.15, wristStress: 0.12, lumbarStress: 0.08 },
    skillRequirement: 0.26,
    mobilityRequirement: 0.3,
    stabilityRequirement: 0.28,
    loadedStretch: 0.7,
    hypertrophyPotential: 0.77,
    frequencySuitability: 0.85,
    progressionPotential: 0.67,
  },
  machine_decline_chest_press: {
    evidenceLevel: EVIDENCE,
    stimulus: { lowerChest: 0.5, triceps: 0.22, frontDelts: 0.14, midChest: 0.14 },
    fatigue: 0.38,
    recoveryDemand: 0.32,
    jointStress: { shoulderStress: 0.36, elbowStress: 0.22, wristStress: 0.1, lumbarStress: 0.08 },
    skillRequirement: 0.18,
    mobilityRequirement: 0.24,
    stabilityRequirement: 0.2,
    loadedStretch: 0.44,
    hypertrophyPotential: 0.75,
    frequencySuitability: 0.84,
    progressionPotential: 0.72,
  },
  cable_crossover_high_to_low: {
    evidenceLevel: EVIDENCE,
    stimulus: { lowerChest: 0.66, frontDelts: 0.16, triceps: 0.1, midChest: 0.08 },
    fatigue: 0.26,
    recoveryDemand: 0.22,
    jointStress: { shoulderStress: 0.36, elbowStress: 0.14, wristStress: 0.1, lumbarStress: 0.08 },
    skillRequirement: 0.24,
    mobilityRequirement: 0.28,
    stabilityRequirement: 0.26,
    loadedStretch: 0.66,
    hypertrophyPotential: 0.76,
    frequencySuitability: 0.86,
    progressionPotential: 0.66,
  },
  // Lats / back
  single_arm_dumbbell_row: {
    evidenceLevel: EVIDENCE,
    stimulus: { lats: 0.4, upperBack: 0.32, biceps: 0.18, rearDelts: 0.1 },
    fatigue: 0.38,
    recoveryDemand: 0.32,
    jointStress: { shoulderStress: 0.32, elbowStress: 0.24, wristStress: 0.16, lumbarStress: 0.26 },
    skillRequirement: 0.3,
    mobilityRequirement: 0.28,
    stabilityRequirement: 0.36,
    loadedStretch: 0.5,
    hypertrophyPotential: 0.8,
    frequencySuitability: 0.82,
    progressionPotential: 0.8,
  },
  pendlay_row: {
    evidenceLevel: EVIDENCE,
    stimulus: { upperBack: 0.36, lats: 0.34, biceps: 0.18, rearDelts: 0.12 },
    fatigue: 0.58,
    recoveryDemand: 0.48,
    jointStress: { shoulderStress: 0.36, elbowStress: 0.28, wristStress: 0.2, lumbarStress: 0.44 },
    skillRequirement: 0.55,
    mobilityRequirement: 0.42,
    stabilityRequirement: 0.5,
    loadedStretch: 0.4,
    hypertrophyPotential: 0.84,
    frequencySuitability: 0.7,
    progressionPotential: 0.88,
  },
  dumbbell_pullover: {
    evidenceLevel: EVIDENCE,
    stimulus: { lats: 0.42, midChest: 0.28, triceps: 0.14, upperBack: 0.1, abs: 0.06 },
    fatigue: 0.34,
    recoveryDemand: 0.28,
    jointStress: { shoulderStress: 0.42, elbowStress: 0.2, wristStress: 0.14, lumbarStress: 0.18 },
    skillRequirement: 0.35,
    mobilityRequirement: 0.4,
    stabilityRequirement: 0.32,
    loadedStretch: 0.72,
    hypertrophyPotential: 0.76,
    frequencySuitability: 0.8,
    progressionPotential: 0.7,
  },
  neutral_grip_pull_up: {
    evidenceLevel: EVIDENCE,
    stimulus: { lats: 0.48, biceps: 0.28, upperBack: 0.16, abs: 0.08 },
    fatigue: 0.56,
    recoveryDemand: 0.46,
    jointStress: { shoulderStress: 0.42, elbowStress: 0.3, wristStress: 0.32, lumbarStress: 0.1 },
    skillRequirement: 0.58,
    mobilityRequirement: 0.42,
    stabilityRequirement: 0.55,
    loadedStretch: 0.48,
    hypertrophyPotential: 0.84,
    frequencySuitability: 0.72,
    progressionPotential: 0.74,
  },
  wide_grip_pull_up: {
    evidenceLevel: EVIDENCE,
    stimulus: { lats: 0.52, upperBack: 0.22, biceps: 0.18, abs: 0.08 },
    fatigue: 0.58,
    recoveryDemand: 0.48,
    jointStress: { shoulderStress: 0.48, elbowStress: 0.28, wristStress: 0.34, lumbarStress: 0.1 },
    skillRequirement: 0.62,
    mobilityRequirement: 0.45,
    stabilityRequirement: 0.58,
    loadedStretch: 0.52,
    hypertrophyPotential: 0.83,
    frequencySuitability: 0.7,
    progressionPotential: 0.72,
  },
  rack_pull: {
    evidenceLevel: EVIDENCE,
    stimulus: { upperBack: 0.42, lats: 0.22, glutes: 0.18, hamstrings: 0.12, forearms: 0.06 },
    fatigue: 0.68,
    recoveryDemand: 0.58,
    jointStress: { lumbarStress: 0.52, hipStress: 0.42, shoulderStress: 0.28, kneeStress: 0.18 },
    skillRequirement: 0.48,
    mobilityRequirement: 0.38,
    stabilityRequirement: 0.45,
    loadedStretch: 0.35,
    hypertrophyPotential: 0.82,
    frequencySuitability: 0.64,
    progressionPotential: 0.9,
  },
  barbell_shrug: {
    evidenceLevel: EVIDENCE,
    stimulus: { upperBack: 0.78, forearms: 0.12, sideDelts: 0.1 },
    fatigue: 0.32,
    recoveryDemand: 0.26,
    jointStress: { shoulderStress: 0.28, wristStress: 0.22, lumbarStress: 0.18, elbowStress: 0.08 },
    skillRequirement: 0.18,
    mobilityRequirement: 0.15,
    stabilityRequirement: 0.22,
    loadedStretch: 0.25,
    hypertrophyPotential: 0.68,
    frequencySuitability: 0.86,
    progressionPotential: 0.78,
  },
  machine_row: {
    evidenceLevel: EVIDENCE,
    stimulus: { upperBack: 0.38, lats: 0.34, biceps: 0.2, rearDelts: 0.08 },
    fatigue: 0.38,
    recoveryDemand: 0.32,
    jointStress: { shoulderStress: 0.3, elbowStress: 0.24, wristStress: 0.14, lumbarStress: 0.2 },
    skillRequirement: 0.18,
    mobilityRequirement: 0.22,
    stabilityRequirement: 0.2,
    loadedStretch: 0.44,
    hypertrophyPotential: 0.78,
    frequencySuitability: 0.84,
    progressionPotential: 0.78,
  },
  cable_row_straight_bar: {
    evidenceLevel: EVIDENCE,
    stimulus: { upperBack: 0.4, lats: 0.32, biceps: 0.2, rearDelts: 0.08 },
    fatigue: 0.36,
    recoveryDemand: 0.3,
    jointStress: { shoulderStress: 0.3, elbowStress: 0.24, wristStress: 0.16, lumbarStress: 0.2 },
    skillRequirement: 0.22,
    mobilityRequirement: 0.24,
    stabilityRequirement: 0.28,
    loadedStretch: 0.42,
    hypertrophyPotential: 0.79,
    frequencySuitability: 0.84,
    progressionPotential: 0.8,
  },
  // Rear delts
  cable_rear_delt_fly: {
    evidenceLevel: EVIDENCE,
    stimulus: { rearDelts: 0.74, upperBack: 0.16, sideDelts: 0.1 },
    fatigue: 0.24,
    recoveryDemand: 0.2,
    jointStress: { shoulderStress: 0.34, elbowStress: 0.1, wristStress: 0.08, lumbarStress: 0.1 },
    skillRequirement: 0.2,
    mobilityRequirement: 0.22,
    stabilityRequirement: 0.24,
    loadedStretch: 0.4,
    hypertrophyPotential: 0.74,
    frequencySuitability: 0.88,
    progressionPotential: 0.64,
  },
  dumbbell_bent_over_lateral_raise: {
    evidenceLevel: EVIDENCE,
    stimulus: { rearDelts: 0.7, upperBack: 0.18, sideDelts: 0.12 },
    fatigue: 0.26,
    recoveryDemand: 0.22,
    jointStress: { shoulderStress: 0.36, elbowStress: 0.1, wristStress: 0.1, lumbarStress: 0.16 },
    skillRequirement: 0.24,
    mobilityRequirement: 0.26,
    stabilityRequirement: 0.28,
    loadedStretch: 0.42,
    hypertrophyPotential: 0.75,
    frequencySuitability: 0.86,
    progressionPotential: 0.65,
  },
  machine_rear_delt_fly: {
    evidenceLevel: EVIDENCE,
    stimulus: { rearDelts: 0.76, upperBack: 0.14, sideDelts: 0.1 },
    fatigue: 0.22,
    recoveryDemand: 0.18,
    jointStress: { shoulderStress: 0.3, elbowStress: 0.08, wristStress: 0.08, lumbarStress: 0.08 },
    skillRequirement: 0.14,
    mobilityRequirement: 0.16,
    stabilityRequirement: 0.16,
    loadedStretch: 0.38,
    hypertrophyPotential: 0.72,
    frequencySuitability: 0.88,
    progressionPotential: 0.62,
  },
  // Biceps
  concentration_curl: {
    evidenceLevel: EVIDENCE,
    stimulus: { biceps: 0.86, forearms: 0.1, upperBack: 0.04 },
    fatigue: 0.26,
    recoveryDemand: 0.22,
    jointStress: { elbowStress: 0.32, wristStress: 0.18, shoulderStress: 0.08, lumbarStress: 0.06 },
    skillRequirement: 0.18,
    mobilityRequirement: 0.14,
    stabilityRequirement: 0.16,
    loadedStretch: 0.55,
    hypertrophyPotential: 0.8,
    frequencySuitability: 0.86,
    progressionPotential: 0.7,
  },
  machine_bicep_curl: {
    evidenceLevel: EVIDENCE,
    stimulus: { biceps: 0.84, forearms: 0.1, upperBack: 0.06 },
    fatigue: 0.24,
    recoveryDemand: 0.2,
    jointStress: { elbowStress: 0.28, wristStress: 0.16, shoulderStress: 0.08, lumbarStress: 0.06 },
    skillRequirement: 0.12,
    mobilityRequirement: 0.12,
    stabilityRequirement: 0.14,
    loadedStretch: 0.48,
    hypertrophyPotential: 0.76,
    frequencySuitability: 0.88,
    progressionPotential: 0.72,
  },
  cable_bicep_curl: {
    evidenceLevel: EVIDENCE,
    stimulus: { biceps: 0.82, forearms: 0.12, upperBack: 0.06 },
    fatigue: 0.26,
    recoveryDemand: 0.22,
    jointStress: { elbowStress: 0.3, wristStress: 0.18, shoulderStress: 0.08, lumbarStress: 0.06 },
    skillRequirement: 0.16,
    mobilityRequirement: 0.14,
    stabilityRequirement: 0.18,
    loadedStretch: 0.5,
    hypertrophyPotential: 0.78,
    frequencySuitability: 0.86,
    progressionPotential: 0.72,
  },
  ez_bar_curl: {
    evidenceLevel: EVIDENCE,
    stimulus: { biceps: 0.8, forearms: 0.14, upperBack: 0.06 },
    fatigue: 0.28,
    recoveryDemand: 0.23,
    jointStress: { elbowStress: 0.3, wristStress: 0.2, shoulderStress: 0.1, lumbarStress: 0.06 },
    skillRequirement: 0.22,
    mobilityRequirement: 0.16,
    stabilityRequirement: 0.2,
    loadedStretch: 0.45,
    hypertrophyPotential: 0.78,
    frequencySuitability: 0.86,
    progressionPotential: 0.76,
  },
  spider_curl: {
    evidenceLevel: EVIDENCE,
    stimulus: { biceps: 0.84, forearms: 0.1, upperBack: 0.06 },
    fatigue: 0.27,
    recoveryDemand: 0.22,
    jointStress: { elbowStress: 0.34, wristStress: 0.18, shoulderStress: 0.08, lumbarStress: 0.06 },
    skillRequirement: 0.2,
    mobilityRequirement: 0.14,
    stabilityRequirement: 0.16,
    loadedStretch: 0.58,
    hypertrophyPotential: 0.81,
    frequencySuitability: 0.86,
    progressionPotential: 0.7,
  },
  // Triceps
  dumbbell_tricep_extension: {
    evidenceLevel: EVIDENCE,
    stimulus: { triceps: 0.84, forearms: 0.1, frontDelts: 0.06 },
    fatigue: 0.28,
    recoveryDemand: 0.24,
    jointStress: { elbowStress: 0.38, shoulderStress: 0.2, wristStress: 0.16, lumbarStress: 0.08 },
    skillRequirement: 0.22,
    mobilityRequirement: 0.18,
    stabilityRequirement: 0.2,
    loadedStretch: 0.42,
    hypertrophyPotential: 0.76,
    frequencySuitability: 0.86,
    progressionPotential: 0.74,
  },
  jm_press: {
    evidenceLevel: EVIDENCE,
    stimulus: { triceps: 0.44, midChest: 0.28, frontDelts: 0.18, upperBack: 0.1 },
    fatigue: 0.58,
    recoveryDemand: 0.48,
    jointStress: { elbowStress: 0.45, shoulderStress: 0.38, wristStress: 0.22, lumbarStress: 0.16 },
    skillRequirement: 0.52,
    mobilityRequirement: 0.34,
    stabilityRequirement: 0.42,
    loadedStretch: 0.35,
    hypertrophyPotential: 0.8,
    frequencySuitability: 0.72,
    progressionPotential: 0.85,
  },
  diamond_push_up: {
    evidenceLevel: EVIDENCE,
    stimulus: { triceps: 0.42, midChest: 0.28, frontDelts: 0.18, abs: 0.12 },
    fatigue: 0.4,
    recoveryDemand: 0.34,
    jointStress: { shoulderStress: 0.42, elbowStress: 0.38, wristStress: 0.32, lumbarStress: 0.12 },
    skillRequirement: 0.42,
    mobilityRequirement: 0.32,
    stabilityRequirement: 0.48,
    loadedStretch: 0.38,
    hypertrophyPotential: 0.72,
    frequencySuitability: 0.8,
    progressionPotential: 0.65,
  },
  cable_tricep_pushdown_rope: {
    evidenceLevel: EVIDENCE,
    stimulus: { triceps: 0.86, forearms: 0.1, rearDelts: 0.04 },
    fatigue: 0.25,
    recoveryDemand: 0.21,
    jointStress: { elbowStress: 0.34, shoulderStress: 0.16, wristStress: 0.14, lumbarStress: 0.06 },
    skillRequirement: 0.14,
    mobilityRequirement: 0.12,
    stabilityRequirement: 0.16,
    loadedStretch: 0.32,
    hypertrophyPotential: 0.74,
    frequencySuitability: 0.88,
    progressionPotential: 0.74,
  },
  ez_bar_skull_crusher: {
    evidenceLevel: EVIDENCE,
    stimulus: { triceps: 0.86, forearms: 0.08, frontDelts: 0.06 },
    fatigue: 0.3,
    recoveryDemand: 0.25,
    jointStress: { elbowStress: 0.46, shoulderStress: 0.22, wristStress: 0.16, lumbarStress: 0.1 },
    skillRequirement: 0.28,
    mobilityRequirement: 0.2,
    stabilityRequirement: 0.22,
    loadedStretch: 0.5,
    hypertrophyPotential: 0.78,
    frequencySuitability: 0.84,
    progressionPotential: 0.76,
  },
  // Quads
  pause_squat: {
    evidenceLevel: EVIDENCE,
    stimulus: { quads: 0.44, glutes: 0.26, hamstrings: 0.12, abs: 0.1, upperBack: 0.08 },
    fatigue: 0.8,
    recoveryDemand: 0.72,
    jointStress: { kneeStress: 0.6, hipStress: 0.52, lumbarStress: 0.5, ankleStress: 0.36 },
    skillRequirement: 0.7,
    mobilityRequirement: 0.64,
    stabilityRequirement: 0.66,
    loadedStretch: 0.42,
    hypertrophyPotential: 0.88,
    frequencySuitability: 0.62,
    progressionPotential: 0.92,
  },
  barbell_lunge: {
    evidenceLevel: EVIDENCE,
    stimulus: { quads: 0.38, glutes: 0.36, hamstrings: 0.14, abs: 0.12 },
    fatigue: 0.56,
    recoveryDemand: 0.46,
    jointStress: { kneeStress: 0.44, hipStress: 0.4, lumbarStress: 0.28, ankleStress: 0.3 },
    skillRequirement: 0.5,
    mobilityRequirement: 0.46,
    stabilityRequirement: 0.54,
    loadedStretch: 0.48,
    hypertrophyPotential: 0.8,
    frequencySuitability: 0.74,
    progressionPotential: 0.82,
  },
  dumbbell_lunge: {
    evidenceLevel: EVIDENCE,
    stimulus: { quads: 0.36, glutes: 0.38, hamstrings: 0.14, abs: 0.12 },
    fatigue: 0.48,
    recoveryDemand: 0.4,
    jointStress: { kneeStress: 0.4, hipStress: 0.38, lumbarStress: 0.24, ankleStress: 0.28 },
    skillRequirement: 0.42,
    mobilityRequirement: 0.4,
    stabilityRequirement: 0.5,
    loadedStretch: 0.5,
    hypertrophyPotential: 0.78,
    frequencySuitability: 0.78,
    progressionPotential: 0.78,
  },
  safety_bar_squat: {
    evidenceLevel: EVIDENCE,
    stimulus: { quads: 0.44, glutes: 0.28, hamstrings: 0.12, abs: 0.1, upperBack: 0.06 },
    fatigue: 0.74,
    recoveryDemand: 0.66,
    jointStress: { kneeStress: 0.56, hipStress: 0.5, lumbarStress: 0.4, ankleStress: 0.34 },
    skillRequirement: 0.62,
    mobilityRequirement: 0.55,
    stabilityRequirement: 0.58,
    loadedStretch: 0.4,
    hypertrophyPotential: 0.87,
    frequencySuitability: 0.64,
    progressionPotential: 0.9,
  },
  box_squat: {
    evidenceLevel: EVIDENCE,
    stimulus: { quads: 0.4, glutes: 0.3, hamstrings: 0.14, abs: 0.1, upperBack: 0.06 },
    fatigue: 0.7,
    recoveryDemand: 0.62,
    jointStress: { kneeStress: 0.52, hipStress: 0.48, lumbarStress: 0.38, ankleStress: 0.3 },
    skillRequirement: 0.58,
    mobilityRequirement: 0.48,
    stabilityRequirement: 0.55,
    loadedStretch: 0.38,
    hypertrophyPotential: 0.84,
    frequencySuitability: 0.66,
    progressionPotential: 0.88,
  },
  // Hamstrings
  deadlift: {
    evidenceLevel: EVIDENCE,
    stimulus: { hamstrings: 0.28, glutes: 0.24, upperBack: 0.22, quads: 0.14, forearms: 0.12 },
    fatigue: 0.82,
    recoveryDemand: 0.72,
    jointStress: { lumbarStress: 0.62, hipStress: 0.55, kneeStress: 0.28, ankleStress: 0.18 },
    skillRequirement: 0.72,
    mobilityRequirement: 0.58,
    stabilityRequirement: 0.62,
    loadedStretch: 0.45,
    hypertrophyPotential: 0.88,
    frequencySuitability: 0.58,
    progressionPotential: 0.96,
  },
  deficit_deadlift: {
    evidenceLevel: EVIDENCE,
    stimulus: { hamstrings: 0.32, glutes: 0.26, upperBack: 0.2, quads: 0.12, forearms: 0.1 },
    fatigue: 0.78,
    recoveryDemand: 0.68,
    jointStress: { lumbarStress: 0.58, hipStress: 0.52, kneeStress: 0.26, ankleStress: 0.22 },
    skillRequirement: 0.68,
    mobilityRequirement: 0.62,
    stabilityRequirement: 0.58,
    loadedStretch: 0.55,
    hypertrophyPotential: 0.86,
    frequencySuitability: 0.6,
    progressionPotential: 0.92,
  },
  machine_leg_curl_lying: {
    evidenceLevel: EVIDENCE,
    stimulus: { hamstrings: 0.9, glutes: 0.06, calves: 0.04 },
    fatigue: 0.28,
    recoveryDemand: 0.24,
    jointStress: { kneeStress: 0.26, hipStress: 0.1, lumbarStress: 0.08, ankleStress: 0.06 },
    skillRequirement: 0.12,
    mobilityRequirement: 0.16,
    stabilityRequirement: 0.14,
    loadedStretch: 0.66,
    hypertrophyPotential: 0.75,
    frequencySuitability: 0.86,
    progressionPotential: 0.7,
  },
  dumbbell_romanian_deadlift: {
    evidenceLevel: EVIDENCE,
    stimulus: { hamstrings: 0.46, glutes: 0.3, upperBack: 0.14, forearms: 0.1 },
    fatigue: 0.58,
    recoveryDemand: 0.5,
    jointStress: { hipStress: 0.44, lumbarStress: 0.48, kneeStress: 0.2, ankleStress: 0.1 },
    skillRequirement: 0.48,
    mobilityRequirement: 0.48,
    stabilityRequirement: 0.45,
    loadedStretch: 0.72,
    hypertrophyPotential: 0.84,
    frequencySuitability: 0.7,
    progressionPotential: 0.84,
  },
  // Glutes
  dumbbell_hip_thrust: {
    evidenceLevel: EVIDENCE,
    stimulus: { glutes: 0.62, hamstrings: 0.22, quads: 0.1, abs: 0.06 },
    fatigue: 0.44,
    recoveryDemand: 0.36,
    jointStress: { hipStress: 0.36, lumbarStress: 0.26, kneeStress: 0.2, ankleStress: 0.1 },
    skillRequirement: 0.28,
    mobilityRequirement: 0.26,
    stabilityRequirement: 0.26,
    loadedStretch: 0.44,
    hypertrophyPotential: 0.86,
    frequencySuitability: 0.8,
    progressionPotential: 0.84,
  },
  dumbbell_glute_bridge: {
    evidenceLevel: EVIDENCE,
    stimulus: { glutes: 0.68, hamstrings: 0.18, quads: 0.08, abs: 0.06 },
    fatigue: 0.32,
    recoveryDemand: 0.26,
    jointStress: { hipStress: 0.28, lumbarStress: 0.2, kneeStress: 0.16, ankleStress: 0.08 },
    skillRequirement: 0.18,
    mobilityRequirement: 0.2,
    stabilityRequirement: 0.22,
    loadedStretch: 0.38,
    hypertrophyPotential: 0.78,
    frequencySuitability: 0.84,
    progressionPotential: 0.72,
  },
  // Calves
  calf_raise: {
    evidenceLevel: EVIDENCE,
    stimulus: { calves: 0.92, forearms: 0.04, abs: 0.04 },
    fatigue: 0.28,
    recoveryDemand: 0.24,
    jointStress: { ankleStress: 0.4, kneeStress: 0.12, hipStress: 0.08, lumbarStress: 0.08 },
    skillRequirement: 0.2,
    mobilityRequirement: 0.18,
    stabilityRequirement: 0.24,
    loadedStretch: 0.52,
    hypertrophyPotential: 0.72,
    frequencySuitability: 0.88,
    progressionPotential: 0.76,
  },
  machine_calf_raise_standing: {
    evidenceLevel: EVIDENCE,
    stimulus: { calves: 0.93, forearms: 0.04, abs: 0.03 },
    fatigue: 0.26,
    recoveryDemand: 0.22,
    jointStress: { ankleStress: 0.38, kneeStress: 0.1, hipStress: 0.06, lumbarStress: 0.06 },
    skillRequirement: 0.14,
    mobilityRequirement: 0.14,
    stabilityRequirement: 0.16,
    loadedStretch: 0.54,
    hypertrophyPotential: 0.7,
    frequencySuitability: 0.9,
    progressionPotential: 0.72,
  },
  seated_calf_raise_machine: {
    evidenceLevel: EVIDENCE,
    stimulus: { calves: 0.94, forearms: 0.03, abs: 0.03 },
    fatigue: 0.24,
    recoveryDemand: 0.2,
    jointStress: { ankleStress: 0.36, kneeStress: 0.1, hipStress: 0.06, lumbarStress: 0.06 },
    skillRequirement: 0.12,
    mobilityRequirement: 0.12,
    stabilityRequirement: 0.14,
    loadedStretch: 0.56,
    hypertrophyPotential: 0.7,
    frequencySuitability: 0.9,
    progressionPotential: 0.7,
  },
  // Abs
  reverse_crunch: {
    evidenceLevel: EVIDENCE,
    stimulus: { abs: 0.78, forearms: 0.1, quads: 0.12 },
    fatigue: 0.28,
    recoveryDemand: 0.24,
    jointStress: { lumbarStress: 0.32, hipStress: 0.22, shoulderStress: 0.1, elbowStress: 0.08 },
    skillRequirement: 0.22,
    mobilityRequirement: 0.2,
    stabilityRequirement: 0.28,
    loadedStretch: 0.32,
    hypertrophyPotential: 0.68,
    frequencySuitability: 0.86,
    progressionPotential: 0.62,
  },
  bicycle_crunch: {
    evidenceLevel: EVIDENCE,
    stimulus: { abs: 0.7, quads: 0.14, forearms: 0.08, sideDelts: 0.08 },
    fatigue: 0.3,
    recoveryDemand: 0.25,
    jointStress: { lumbarStress: 0.28, hipStress: 0.2, shoulderStress: 0.1, elbowStress: 0.08 },
    skillRequirement: 0.2,
    mobilityRequirement: 0.22,
    stabilityRequirement: 0.26,
    loadedStretch: 0.28,
    hypertrophyPotential: 0.65,
    frequencySuitability: 0.86,
    progressionPotential: 0.58,
  },
  v_up: {
    evidenceLevel: EVIDENCE,
    stimulus: { abs: 0.72, quads: 0.14, forearms: 0.08, lats: 0.06 },
    fatigue: 0.34,
    recoveryDemand: 0.28,
    jointStress: { lumbarStress: 0.3, hipStress: 0.24, shoulderStress: 0.12, wristStress: 0.1 },
    skillRequirement: 0.38,
    mobilityRequirement: 0.32,
    stabilityRequirement: 0.36,
    loadedStretch: 0.3,
    hypertrophyPotential: 0.66,
    frequencySuitability: 0.82,
    progressionPotential: 0.58,
  },
  // Forearms
  barbell_wrist_curl: {
    evidenceLevel: EVIDENCE,
    stimulus: { forearms: 0.88, biceps: 0.08, upperBack: 0.04 },
    fatigue: 0.24,
    recoveryDemand: 0.2,
    jointStress: { wristStress: 0.42, elbowStress: 0.22, shoulderStress: 0.08, lumbarStress: 0.06 },
    skillRequirement: 0.16,
    mobilityRequirement: 0.14,
    stabilityRequirement: 0.18,
    loadedStretch: 0.35,
    hypertrophyPotential: 0.68,
    frequencySuitability: 0.88,
    progressionPotential: 0.7,
  },
  zottman_curl: {
    evidenceLevel: EVIDENCE,
    stimulus: { forearms: 0.42, biceps: 0.48, upperBack: 0.1 },
    fatigue: 0.28,
    recoveryDemand: 0.23,
    jointStress: { elbowStress: 0.32, wristStress: 0.28, shoulderStress: 0.1, lumbarStress: 0.06 },
    skillRequirement: 0.24,
    mobilityRequirement: 0.18,
    stabilityRequirement: 0.22,
    loadedStretch: 0.42,
    hypertrophyPotential: 0.76,
    frequencySuitability: 0.86,
    progressionPotential: 0.72,
  },
  // Tibialis
  tibia_raise: {
    evidenceLevel: EVIDENCE,
    stimulus: { tibialis: 0.88, calves: 0.08, abs: 0.04 },
    fatigue: 0.24,
    recoveryDemand: 0.2,
    jointStress: { ankleStress: 0.38, kneeStress: 0.12, hipStress: 0.06, lumbarStress: 0.06 },
    skillRequirement: 0.14,
    mobilityRequirement: 0.16,
    stabilityRequirement: 0.18,
    loadedStretch: 0.4,
    hypertrophyPotential: 0.62,
    frequencySuitability: 0.9,
    progressionPotential: 0.65,
  },
};
