/**
 * Hypertrophy Core v1 — bundled ExerciseIntelligenceV1 seed (100 exercises).
 * Scores are heuristic / library_derived for v1; expand with expert curation later.
 */

import { EXERCISE_LIBRARY_V1 } from "../library.v1";
import {
  EXERCISE_INTELLIGENCE_SCHEMA_VERSION,
  validateExerciseIntelligenceV1,
  type ExerciseIntelligenceV1,
  type ExerciseIntelligenceEvidenceLevel,
} from "./exerciseIntelligenceV1Types";
import { computeStimulusToFatigueRatio } from "./exerciseIntelligenceScoring";
import { HYPERTROPHY_CORE_V1_PHASE6_SEEDS } from "./hypertrophyCoreV1Phase6Seeds";

type IntelligenceSeed = Omit<ExerciseIntelligenceV1, "schemaVersion" | "exerciseId" | "stimulusToFatigueRatio">;

function defineIntelligence(
  exerciseId: string,
  seed: IntelligenceSeed,
): ExerciseIntelligenceV1 {
  const row: ExerciseIntelligenceV1 = {
    exerciseId,
    schemaVersion: EXERCISE_INTELLIGENCE_SCHEMA_VERSION,
    ...seed,
    stimulusToFatigueRatio: computeStimulusToFatigueRatio(seed.stimulus, seed.fatigue),
  };
  if (!validateExerciseIntelligenceV1(row)) {
    throw new Error(`Invalid ExerciseIntelligenceV1 seed: ${exerciseId}`);
  }
  return row;
}

function defineHypertrophyCoreMap(
  entries: Record<string, IntelligenceSeed>,
): readonly ExerciseIntelligenceV1[] {
  const libraryIds = new Set(EXERCISE_LIBRARY_V1.map((x) => x.exerciseId));
  const out: ExerciseIntelligenceV1[] = [];
  for (const [exerciseId, seed] of Object.entries(entries)) {
    if (!libraryIds.has(exerciseId)) {
      throw new Error(`Hypertrophy core references unknown library exerciseId: ${exerciseId}`);
    }
    out.push(defineIntelligence(exerciseId, seed));
  }
  return Object.freeze(out);
}

const EVIDENCE: ExerciseIntelligenceEvidenceLevel = "heuristic";

/** First-wave hypertrophy anchors — keyed by stable catalog ids only. */
export const HYPERTROPHY_CORE_INTELLIGENCE_V1: readonly ExerciseIntelligenceV1[] =
  defineHypertrophyCoreMap({
    bench_press: {
      evidenceLevel: EVIDENCE,
      stimulus: { midChest: 0.45, triceps: 0.28, frontDelts: 0.18, upperBack: 0.09 },
      fatigue: 0.62,
      recoveryDemand: 0.52,
      jointStress: {
        shoulderStress: 0.52,
        elbowStress: 0.32,
        wristStress: 0.22,
        lumbarStress: 0.18,
      },
      skillRequirement: 0.52,
      mobilityRequirement: 0.38,
      stabilityRequirement: 0.48,
      loadedStretch: 0.42,
      hypertrophyPotential: 0.88,
      frequencySuitability: 0.78,
      progressionPotential: 0.95,
    },
    incline_bench_press: {
      evidenceLevel: EVIDENCE,
      stimulus: { upperChest: 0.48, triceps: 0.24, frontDelts: 0.2, midChest: 0.08 },
      fatigue: 0.6,
      recoveryDemand: 0.5,
      jointStress: {
        shoulderStress: 0.55,
        elbowStress: 0.3,
        wristStress: 0.22,
        lumbarStress: 0.16,
      },
      skillRequirement: 0.5,
      mobilityRequirement: 0.42,
      stabilityRequirement: 0.46,
      loadedStretch: 0.48,
      hypertrophyPotential: 0.86,
      frequencySuitability: 0.76,
      progressionPotential: 0.92,
    },
    dumbbell_bench_press: {
      evidenceLevel: EVIDENCE,
      stimulus: { midChest: 0.5, triceps: 0.22, frontDelts: 0.18, upperBack: 0.1 },
      fatigue: 0.55,
      recoveryDemand: 0.45,
      jointStress: {
        shoulderStress: 0.48,
        elbowStress: 0.28,
        wristStress: 0.2,
        lumbarStress: 0.14,
      },
      skillRequirement: 0.42,
      mobilityRequirement: 0.4,
      stabilityRequirement: 0.55,
      loadedStretch: 0.55,
      hypertrophyPotential: 0.84,
      frequencySuitability: 0.8,
      progressionPotential: 0.88,
    },
    machine_chest_press: {
      evidenceLevel: EVIDENCE,
      stimulus: { midChest: 0.52, triceps: 0.26, frontDelts: 0.14, lowerChest: 0.08 },
      fatigue: 0.42,
      recoveryDemand: 0.35,
      jointStress: {
        shoulderStress: 0.35,
        elbowStress: 0.25,
        wristStress: 0.12,
        lumbarStress: 0.08,
      },
      skillRequirement: 0.2,
      mobilityRequirement: 0.25,
      stabilityRequirement: 0.22,
      loadedStretch: 0.38,
      hypertrophyPotential: 0.78,
      frequencySuitability: 0.85,
      progressionPotential: 0.72,
    },
    lat_pulldown: {
      evidenceLevel: EVIDENCE,
      stimulus: { lats: 0.52, biceps: 0.22, upperBack: 0.18, rearDelts: 0.08 },
      fatigue: 0.45,
      recoveryDemand: 0.38,
      jointStress: {
        shoulderStress: 0.38,
        elbowStress: 0.28,
        wristStress: 0.18,
        lumbarStress: 0.12,
      },
      skillRequirement: 0.28,
      mobilityRequirement: 0.32,
      stabilityRequirement: 0.3,
      loadedStretch: 0.52,
      hypertrophyPotential: 0.82,
      frequencySuitability: 0.82,
      progressionPotential: 0.8,
    },
    pull_up: {
      evidenceLevel: EVIDENCE,
      stimulus: { lats: 0.5, biceps: 0.24, upperBack: 0.18, abs: 0.08 },
      fatigue: 0.58,
      recoveryDemand: 0.48,
      jointStress: {
        shoulderStress: 0.45,
        elbowStress: 0.32,
        wristStress: 0.35,
        lumbarStress: 0.1,
      },
      skillRequirement: 0.62,
      mobilityRequirement: 0.45,
      stabilityRequirement: 0.58,
      loadedStretch: 0.5,
      hypertrophyPotential: 0.85,
      frequencySuitability: 0.7,
      progressionPotential: 0.75,
    },
    seated_cable_row: {
      evidenceLevel: EVIDENCE,
      stimulus: { upperBack: 0.42, lats: 0.32, biceps: 0.18, rearDelts: 0.08 },
      fatigue: 0.4,
      recoveryDemand: 0.34,
      jointStress: {
        shoulderStress: 0.32,
        elbowStress: 0.26,
        wristStress: 0.16,
        lumbarStress: 0.22,
      },
      skillRequirement: 0.25,
      mobilityRequirement: 0.28,
      stabilityRequirement: 0.32,
      loadedStretch: 0.45,
      hypertrophyPotential: 0.8,
      frequencySuitability: 0.84,
      progressionPotential: 0.82,
    },
    squat: {
      evidenceLevel: EVIDENCE,
      stimulus: { quads: 0.42, glutes: 0.28, hamstrings: 0.12, abs: 0.1, upperBack: 0.08 },
      fatigue: 0.78,
      recoveryDemand: 0.72,
      jointStress: {
        kneeStress: 0.58,
        hipStress: 0.52,
        lumbarStress: 0.48,
        ankleStress: 0.35,
      },
      skillRequirement: 0.68,
      mobilityRequirement: 0.62,
      stabilityRequirement: 0.65,
      loadedStretch: 0.4,
      hypertrophyPotential: 0.9,
      frequencySuitability: 0.65,
      progressionPotential: 0.96,
    },
    leg_press: {
      evidenceLevel: EVIDENCE,
      stimulus: { quads: 0.48, glutes: 0.32, hamstrings: 0.12, calves: 0.08 },
      fatigue: 0.55,
      recoveryDemand: 0.42,
      jointStress: {
        kneeStress: 0.45,
        hipStress: 0.38,
        lumbarStress: 0.35,
        ankleStress: 0.2,
      },
      skillRequirement: 0.22,
      mobilityRequirement: 0.3,
      stabilityRequirement: 0.25,
      loadedStretch: 0.35,
      hypertrophyPotential: 0.8,
      frequencySuitability: 0.8,
      progressionPotential: 0.85,
    },
    leg_extension: {
      evidenceLevel: EVIDENCE,
      stimulus: { quads: 0.88, forearms: 0.06, abs: 0.06 },
      fatigue: 0.32,
      recoveryDemand: 0.28,
      jointStress: {
        kneeStress: 0.42,
        hipStress: 0.12,
        lumbarStress: 0.08,
      },
      skillRequirement: 0.15,
      mobilityRequirement: 0.2,
      stabilityRequirement: 0.18,
      loadedStretch: 0.62,
      hypertrophyPotential: 0.75,
      frequencySuitability: 0.88,
      progressionPotential: 0.7,
    },
    romanian_deadlift: {
      evidenceLevel: EVIDENCE,
      stimulus: { hamstrings: 0.48, glutes: 0.32, upperBack: 0.12, forearms: 0.08 },
      fatigue: 0.65,
      recoveryDemand: 0.58,
      jointStress: {
        hipStress: 0.48,
        lumbarStress: 0.55,
        kneeStress: 0.22,
      },
      skillRequirement: 0.58,
      mobilityRequirement: 0.55,
      stabilityRequirement: 0.52,
      loadedStretch: 0.78,
      hypertrophyPotential: 0.86,
      frequencySuitability: 0.68,
      progressionPotential: 0.88,
    },
    leg_curl: {
      evidenceLevel: EVIDENCE,
      stimulus: { hamstrings: 0.9, glutes: 0.06, calves: 0.04 },
      fatigue: 0.3,
      recoveryDemand: 0.26,
      jointStress: {
        kneeStress: 0.28,
        hipStress: 0.12,
        lumbarStress: 0.08,
      },
      skillRequirement: 0.12,
      mobilityRequirement: 0.18,
      stabilityRequirement: 0.15,
      loadedStretch: 0.68,
      hypertrophyPotential: 0.76,
      frequencySuitability: 0.86,
      progressionPotential: 0.72,
    },
    lateral_raise: {
      evidenceLevel: EVIDENCE,
      stimulus: { sideDelts: 0.78, upperBack: 0.12, frontDelts: 0.1 },
      fatigue: 0.28,
      recoveryDemand: 0.24,
      jointStress: {
        shoulderStress: 0.38,
        elbowStress: 0.12,
        wristStress: 0.1,
        lumbarStress: 0.08,
      },
      skillRequirement: 0.22,
      mobilityRequirement: 0.25,
      stabilityRequirement: 0.28,
      loadedStretch: 0.35,
      hypertrophyPotential: 0.8,
      frequencySuitability: 0.9,
      progressionPotential: 0.68,
    },
    tricep_pushdown: {
      evidenceLevel: EVIDENCE,
      stimulus: { triceps: 0.88, forearms: 0.08, rearDelts: 0.04 },
      fatigue: 0.26,
      recoveryDemand: 0.22,
      jointStress: {
        elbowStress: 0.35,
        shoulderStress: 0.18,
        wristStress: 0.15,
      },
      skillRequirement: 0.15,
      mobilityRequirement: 0.12,
      stabilityRequirement: 0.18,
      loadedStretch: 0.3,
      hypertrophyPotential: 0.74,
      frequencySuitability: 0.88,
      progressionPotential: 0.75,
    },
    barbell_curl: {
      evidenceLevel: EVIDENCE,
      stimulus: { biceps: 0.82, forearms: 0.12, upperBack: 0.06 },
      fatigue: 0.3,
      recoveryDemand: 0.25,
      jointStress: {
        elbowStress: 0.32,
        wristStress: 0.22,
        shoulderStress: 0.12,
        lumbarStress: 0.08,
      },
      skillRequirement: 0.25,
      mobilityRequirement: 0.18,
      stabilityRequirement: 0.22,
      loadedStretch: 0.4,
      hypertrophyPotential: 0.78,
      frequencySuitability: 0.86,
      progressionPotential: 0.8,
    },
    // --- Phase 4 expansion (35 additional catalog anchors) ---
    decline_bench_press: {
      evidenceLevel: EVIDENCE,
      stimulus: { lowerChest: 0.46, triceps: 0.26, frontDelts: 0.18, midChest: 0.1 },
      fatigue: 0.58,
      recoveryDemand: 0.48,
      jointStress: { shoulderStress: 0.5, elbowStress: 0.3, wristStress: 0.2, lumbarStress: 0.16 },
      skillRequirement: 0.48,
      mobilityRequirement: 0.36,
      stabilityRequirement: 0.44,
      loadedStretch: 0.44,
      hypertrophyPotential: 0.84,
      frequencySuitability: 0.76,
      progressionPotential: 0.9,
    },
    dumbbell_incline_bench_press: {
      evidenceLevel: EVIDENCE,
      stimulus: { upperChest: 0.5, triceps: 0.22, frontDelts: 0.18, midChest: 0.1 },
      fatigue: 0.52,
      recoveryDemand: 0.44,
      jointStress: { shoulderStress: 0.5, elbowStress: 0.28, wristStress: 0.2, lumbarStress: 0.12 },
      skillRequirement: 0.4,
      mobilityRequirement: 0.4,
      stabilityRequirement: 0.52,
      loadedStretch: 0.58,
      hypertrophyPotential: 0.85,
      frequencySuitability: 0.78,
      progressionPotential: 0.86,
    },
    dumbbell_fly: {
      evidenceLevel: EVIDENCE,
      stimulus: { midChest: 0.72, frontDelts: 0.14, biceps: 0.08, upperBack: 0.06 },
      fatigue: 0.28,
      recoveryDemand: 0.22,
      jointStress: { shoulderStress: 0.42, elbowStress: 0.18, wristStress: 0.14, lumbarStress: 0.1 },
      skillRequirement: 0.32,
      mobilityRequirement: 0.38,
      stabilityRequirement: 0.4,
      loadedStretch: 0.72,
      hypertrophyPotential: 0.8,
      frequencySuitability: 0.84,
      progressionPotential: 0.7,
    },
    push_up: {
      evidenceLevel: EVIDENCE,
      stimulus: { midChest: 0.48, triceps: 0.24, frontDelts: 0.16, abs: 0.12 },
      fatigue: 0.38,
      recoveryDemand: 0.3,
      jointStress: { shoulderStress: 0.4, elbowStress: 0.28, wristStress: 0.3, lumbarStress: 0.12 },
      skillRequirement: 0.35,
      mobilityRequirement: 0.3,
      stabilityRequirement: 0.48,
      loadedStretch: 0.4,
      hypertrophyPotential: 0.72,
      frequencySuitability: 0.82,
      progressionPotential: 0.65,
    },
    close_grip_bench_press: {
      evidenceLevel: EVIDENCE,
      stimulus: { triceps: 0.42, midChest: 0.32, frontDelts: 0.16, upperBack: 0.1 },
      fatigue: 0.6,
      recoveryDemand: 0.5,
      jointStress: { shoulderStress: 0.48, elbowStress: 0.42, wristStress: 0.24, lumbarStress: 0.16 },
      skillRequirement: 0.5,
      mobilityRequirement: 0.36,
      stabilityRequirement: 0.46,
      loadedStretch: 0.38,
      hypertrophyPotential: 0.82,
      frequencySuitability: 0.74,
      progressionPotential: 0.92,
    },
    barbell_row: {
      evidenceLevel: EVIDENCE,
      stimulus: { upperBack: 0.38, lats: 0.34, biceps: 0.18, rearDelts: 0.1 },
      fatigue: 0.55,
      recoveryDemand: 0.46,
      jointStress: { shoulderStress: 0.38, elbowStress: 0.28, wristStress: 0.2, lumbarStress: 0.42 },
      skillRequirement: 0.52,
      mobilityRequirement: 0.4,
      stabilityRequirement: 0.48,
      loadedStretch: 0.42,
      hypertrophyPotential: 0.86,
      frequencySuitability: 0.72,
      progressionPotential: 0.9,
    },
    dumbbell_row: {
      evidenceLevel: EVIDENCE,
      stimulus: { lats: 0.36, upperBack: 0.36, biceps: 0.18, rearDelts: 0.1 },
      fatigue: 0.42,
      recoveryDemand: 0.36,
      jointStress: { shoulderStress: 0.35, elbowStress: 0.26, wristStress: 0.18, lumbarStress: 0.28 },
      skillRequirement: 0.32,
      mobilityRequirement: 0.32,
      stabilityRequirement: 0.38,
      loadedStretch: 0.48,
      hypertrophyPotential: 0.82,
      frequencySuitability: 0.8,
      progressionPotential: 0.82,
    },
    face_pull: {
      evidenceLevel: EVIDENCE,
      stimulus: { rearDelts: 0.48, upperBack: 0.32, sideDelts: 0.12, biceps: 0.08 },
      fatigue: 0.24,
      recoveryDemand: 0.2,
      jointStress: { shoulderStress: 0.32, elbowStress: 0.14, wristStress: 0.1, lumbarStress: 0.1 },
      skillRequirement: 0.2,
      mobilityRequirement: 0.22,
      stabilityRequirement: 0.24,
      loadedStretch: 0.38,
      hypertrophyPotential: 0.72,
      frequencySuitability: 0.9,
      progressionPotential: 0.62,
    },
    chin_up: {
      evidenceLevel: EVIDENCE,
      stimulus: { lats: 0.46, biceps: 0.32, upperBack: 0.16, abs: 0.06 },
      fatigue: 0.56,
      recoveryDemand: 0.46,
      jointStress: { shoulderStress: 0.44, elbowStress: 0.34, wristStress: 0.32, lumbarStress: 0.1 },
      skillRequirement: 0.58,
      mobilityRequirement: 0.42,
      stabilityRequirement: 0.55,
      loadedStretch: 0.48,
      hypertrophyPotential: 0.84,
      frequencySuitability: 0.72,
      progressionPotential: 0.74,
    },
    overhead_press: {
      evidenceLevel: EVIDENCE,
      stimulus: { frontDelts: 0.46, triceps: 0.28, sideDelts: 0.16, upperBack: 0.1 },
      fatigue: 0.64,
      recoveryDemand: 0.54,
      jointStress: { shoulderStress: 0.58, elbowStress: 0.32, wristStress: 0.22, lumbarStress: 0.28 },
      skillRequirement: 0.58,
      mobilityRequirement: 0.48,
      stabilityRequirement: 0.55,
      loadedStretch: 0.35,
      hypertrophyPotential: 0.84,
      frequencySuitability: 0.68,
      progressionPotential: 0.9,
    },
    dumbbell_shoulder_press: {
      evidenceLevel: EVIDENCE,
      stimulus: { frontDelts: 0.44, triceps: 0.26, sideDelts: 0.18, upperBack: 0.12 },
      fatigue: 0.52,
      recoveryDemand: 0.44,
      jointStress: { shoulderStress: 0.52, elbowStress: 0.28, wristStress: 0.2, lumbarStress: 0.2 },
      skillRequirement: 0.42,
      mobilityRequirement: 0.42,
      stabilityRequirement: 0.5,
      loadedStretch: 0.4,
      hypertrophyPotential: 0.82,
      frequencySuitability: 0.74,
      progressionPotential: 0.84,
    },
    rear_delt_fly: {
      evidenceLevel: EVIDENCE,
      stimulus: { rearDelts: 0.72, upperBack: 0.18, sideDelts: 0.1 },
      fatigue: 0.26,
      recoveryDemand: 0.22,
      jointStress: { shoulderStress: 0.36, elbowStress: 0.12, wristStress: 0.1, lumbarStress: 0.14 },
      skillRequirement: 0.22,
      mobilityRequirement: 0.24,
      stabilityRequirement: 0.26,
      loadedStretch: 0.42,
      hypertrophyPotential: 0.76,
      frequencySuitability: 0.88,
      progressionPotential: 0.65,
    },
    cable_lateral_raise: {
      evidenceLevel: EVIDENCE,
      stimulus: { sideDelts: 0.8, upperBack: 0.12, frontDelts: 0.08 },
      fatigue: 0.26,
      recoveryDemand: 0.22,
      jointStress: { shoulderStress: 0.36, elbowStress: 0.1, wristStress: 0.1, lumbarStress: 0.08 },
      skillRequirement: 0.2,
      mobilityRequirement: 0.22,
      stabilityRequirement: 0.26,
      loadedStretch: 0.38,
      hypertrophyPotential: 0.78,
      frequencySuitability: 0.9,
      progressionPotential: 0.66,
    },
    hammer_curl: {
      evidenceLevel: EVIDENCE,
      stimulus: { biceps: 0.48, forearms: 0.38, upperBack: 0.14 },
      fatigue: 0.28,
      recoveryDemand: 0.24,
      jointStress: { elbowStress: 0.3, wristStress: 0.24, shoulderStress: 0.1, lumbarStress: 0.06 },
      skillRequirement: 0.2,
      mobilityRequirement: 0.16,
      stabilityRequirement: 0.2,
      loadedStretch: 0.36,
      hypertrophyPotential: 0.76,
      frequencySuitability: 0.86,
      progressionPotential: 0.74,
    },
    preacher_curl: {
      evidenceLevel: EVIDENCE,
      stimulus: { biceps: 0.85, forearms: 0.1, upperBack: 0.05 },
      fatigue: 0.28,
      recoveryDemand: 0.23,
      jointStress: { elbowStress: 0.34, wristStress: 0.2, shoulderStress: 0.08, lumbarStress: 0.06 },
      skillRequirement: 0.18,
      mobilityRequirement: 0.14,
      stabilityRequirement: 0.16,
      loadedStretch: 0.52,
      hypertrophyPotential: 0.8,
      frequencySuitability: 0.86,
      progressionPotential: 0.72,
    },
    dumbbell_curl: {
      evidenceLevel: EVIDENCE,
      stimulus: { biceps: 0.8, forearms: 0.12, upperBack: 0.08 },
      fatigue: 0.28,
      recoveryDemand: 0.23,
      jointStress: { elbowStress: 0.3, wristStress: 0.22, shoulderStress: 0.1, lumbarStress: 0.06 },
      skillRequirement: 0.2,
      mobilityRequirement: 0.16,
      stabilityRequirement: 0.22,
      loadedStretch: 0.44,
      hypertrophyPotential: 0.78,
      frequencySuitability: 0.86,
      progressionPotential: 0.76,
    },
    incline_dumbbell_curl: {
      evidenceLevel: EVIDENCE,
      stimulus: { biceps: 0.82, forearms: 0.1, upperBack: 0.08 },
      fatigue: 0.27,
      recoveryDemand: 0.22,
      jointStress: { elbowStress: 0.32, wristStress: 0.2, shoulderStress: 0.1, lumbarStress: 0.06 },
      skillRequirement: 0.22,
      mobilityRequirement: 0.18,
      stabilityRequirement: 0.2,
      loadedStretch: 0.58,
      hypertrophyPotential: 0.82,
      frequencySuitability: 0.86,
      progressionPotential: 0.72,
    },
    overhead_dumbbell_tricep_extension: {
      evidenceLevel: EVIDENCE,
      stimulus: { triceps: 0.82, forearms: 0.1, frontDelts: 0.08 },
      fatigue: 0.3,
      recoveryDemand: 0.25,
      jointStress: { elbowStress: 0.42, shoulderStress: 0.38, wristStress: 0.18, lumbarStress: 0.12 },
      skillRequirement: 0.28,
      mobilityRequirement: 0.32,
      stabilityRequirement: 0.3,
      loadedStretch: 0.55,
      hypertrophyPotential: 0.8,
      frequencySuitability: 0.84,
      progressionPotential: 0.74,
    },
    skull_crusher: {
      evidenceLevel: EVIDENCE,
      stimulus: { triceps: 0.86, forearms: 0.08, frontDelts: 0.06 },
      fatigue: 0.32,
      recoveryDemand: 0.27,
      jointStress: { elbowStress: 0.48, shoulderStress: 0.22, wristStress: 0.16, lumbarStress: 0.1 },
      skillRequirement: 0.3,
      mobilityRequirement: 0.22,
      stabilityRequirement: 0.24,
      loadedStretch: 0.48,
      hypertrophyPotential: 0.78,
      frequencySuitability: 0.82,
      progressionPotential: 0.76,
    },
    dip: {
      evidenceLevel: EVIDENCE,
      stimulus: { triceps: 0.38, lowerChest: 0.32, frontDelts: 0.18, midChest: 0.12 },
      fatigue: 0.52,
      recoveryDemand: 0.44,
      jointStress: { shoulderStress: 0.52, elbowStress: 0.4, wristStress: 0.28, lumbarStress: 0.14 },
      skillRequirement: 0.48,
      mobilityRequirement: 0.38,
      stabilityRequirement: 0.5,
      loadedStretch: 0.42,
      hypertrophyPotential: 0.8,
      frequencySuitability: 0.74,
      progressionPotential: 0.78,
    },
    front_squat: {
      evidenceLevel: EVIDENCE,
      stimulus: { quads: 0.46, glutes: 0.24, abs: 0.16, upperBack: 0.14 },
      fatigue: 0.72,
      recoveryDemand: 0.66,
      jointStress: { kneeStress: 0.55, hipStress: 0.45, lumbarStress: 0.38, ankleStress: 0.38 },
      skillRequirement: 0.72,
      mobilityRequirement: 0.68,
      stabilityRequirement: 0.62,
      loadedStretch: 0.38,
      hypertrophyPotential: 0.86,
      frequencySuitability: 0.62,
      progressionPotential: 0.88,
    },
    hack_squat: {
      evidenceLevel: EVIDENCE,
      stimulus: { quads: 0.52, glutes: 0.28, hamstrings: 0.12, calves: 0.08 },
      fatigue: 0.58,
      recoveryDemand: 0.46,
      jointStress: { kneeStress: 0.5, hipStress: 0.4, lumbarStress: 0.32, ankleStress: 0.22 },
      skillRequirement: 0.28,
      mobilityRequirement: 0.32,
      stabilityRequirement: 0.26,
      loadedStretch: 0.36,
      hypertrophyPotential: 0.82,
      frequencySuitability: 0.78,
      progressionPotential: 0.86,
    },
    bulgarian_split_squat_barbell: {
      evidenceLevel: EVIDENCE,
      stimulus: { quads: 0.4, glutes: 0.36, hamstrings: 0.12, abs: 0.12 },
      fatigue: 0.62,
      recoveryDemand: 0.52,
      jointStress: { kneeStress: 0.48, hipStress: 0.42, lumbarStress: 0.28, ankleStress: 0.3 },
      skillRequirement: 0.55,
      mobilityRequirement: 0.52,
      stabilityRequirement: 0.58,
      loadedStretch: 0.52,
      hypertrophyPotential: 0.84,
      frequencySuitability: 0.72,
      progressionPotential: 0.82,
    },
    stiff_leg_deadlift: {
      evidenceLevel: EVIDENCE,
      stimulus: { hamstrings: 0.5, glutes: 0.28, upperBack: 0.14, forearms: 0.08 },
      fatigue: 0.62,
      recoveryDemand: 0.55,
      jointStress: { hipStress: 0.46, lumbarStress: 0.52, kneeStress: 0.2, ankleStress: 0.12 },
      skillRequirement: 0.55,
      mobilityRequirement: 0.52,
      stabilityRequirement: 0.48,
      loadedStretch: 0.75,
      hypertrophyPotential: 0.84,
      frequencySuitability: 0.66,
      progressionPotential: 0.86,
    },
    good_morning: {
      evidenceLevel: EVIDENCE,
      stimulus: { hamstrings: 0.38, glutes: 0.28, upperBack: 0.22, abs: 0.12 },
      fatigue: 0.58,
      recoveryDemand: 0.52,
      jointStress: { lumbarStress: 0.58, hipStress: 0.42, kneeStress: 0.18, ankleStress: 0.1 },
      skillRequirement: 0.62,
      mobilityRequirement: 0.55,
      stabilityRequirement: 0.52,
      loadedStretch: 0.62,
      hypertrophyPotential: 0.72,
      frequencySuitability: 0.62,
      progressionPotential: 0.78,
    },
    hip_thrust: {
      evidenceLevel: EVIDENCE,
      stimulus: { glutes: 0.62, hamstrings: 0.22, quads: 0.1, abs: 0.06 },
      fatigue: 0.48,
      recoveryDemand: 0.4,
      jointStress: { hipStress: 0.38, lumbarStress: 0.28, kneeStress: 0.22, ankleStress: 0.1 },
      skillRequirement: 0.32,
      mobilityRequirement: 0.3,
      stabilityRequirement: 0.28,
      loadedStretch: 0.45,
      hypertrophyPotential: 0.88,
      frequencySuitability: 0.78,
      progressionPotential: 0.88,
    },
    nordic_curl: {
      evidenceLevel: EVIDENCE,
      stimulus: { hamstrings: 0.88, glutes: 0.08, calves: 0.04 },
      fatigue: 0.36,
      recoveryDemand: 0.32,
      jointStress: { kneeStress: 0.38, hipStress: 0.18, lumbarStress: 0.12, ankleStress: 0.1 },
      skillRequirement: 0.55,
      mobilityRequirement: 0.4,
      stabilityRequirement: 0.42,
      loadedStretch: 0.7,
      hypertrophyPotential: 0.74,
      frequencySuitability: 0.7,
      progressionPotential: 0.6,
    },
    sumo_deadlift: {
      evidenceLevel: EVIDENCE,
      stimulus: { glutes: 0.36, quads: 0.28, hamstrings: 0.18, upperBack: 0.12, forearms: 0.06 },
      fatigue: 0.7,
      recoveryDemand: 0.62,
      jointStress: { hipStress: 0.48, kneeStress: 0.4, lumbarStress: 0.42, ankleStress: 0.2 },
      skillRequirement: 0.6,
      mobilityRequirement: 0.48,
      stabilityRequirement: 0.52,
      loadedStretch: 0.42,
      hypertrophyPotential: 0.86,
      frequencySuitability: 0.64,
      progressionPotential: 0.92,
    },
    reverse_lunge_barbell: {
      evidenceLevel: EVIDENCE,
      stimulus: { glutes: 0.38, quads: 0.36, hamstrings: 0.14, abs: 0.12 },
      fatigue: 0.55,
      recoveryDemand: 0.46,
      jointStress: { kneeStress: 0.42, hipStress: 0.4, lumbarStress: 0.26, ankleStress: 0.28 },
      skillRequirement: 0.48,
      mobilityRequirement: 0.45,
      stabilityRequirement: 0.52,
      loadedStretch: 0.48,
      hypertrophyPotential: 0.8,
      frequencySuitability: 0.76,
      progressionPotential: 0.8,
    },
    standing_calf_raise_barbell: {
      evidenceLevel: EVIDENCE,
      stimulus: { calves: 0.92, forearms: 0.04, abs: 0.04 },
      fatigue: 0.28,
      recoveryDemand: 0.24,
      jointStress: { ankleStress: 0.42, kneeStress: 0.12, hipStress: 0.08, lumbarStress: 0.1 },
      skillRequirement: 0.22,
      mobilityRequirement: 0.2,
      stabilityRequirement: 0.28,
      loadedStretch: 0.55,
      hypertrophyPotential: 0.72,
      frequencySuitability: 0.88,
      progressionPotential: 0.78,
    },
    machine_calf_raise_seated: {
      evidenceLevel: EVIDENCE,
      stimulus: { calves: 0.94, forearms: 0.03, abs: 0.03 },
      fatigue: 0.24,
      recoveryDemand: 0.2,
      jointStress: { ankleStress: 0.38, kneeStress: 0.1, hipStress: 0.06, lumbarStress: 0.06 },
      skillRequirement: 0.12,
      mobilityRequirement: 0.14,
      stabilityRequirement: 0.14,
      loadedStretch: 0.58,
      hypertrophyPotential: 0.7,
      frequencySuitability: 0.9,
      progressionPotential: 0.72,
    },
    cable_crunch: {
      evidenceLevel: EVIDENCE,
      stimulus: { abs: 0.88, upperBack: 0.08, forearms: 0.04 },
      fatigue: 0.26,
      recoveryDemand: 0.22,
      jointStress: { lumbarStress: 0.32, hipStress: 0.12, shoulderStress: 0.1, elbowStress: 0.08 },
      skillRequirement: 0.18,
      mobilityRequirement: 0.16,
      stabilityRequirement: 0.2,
      loadedStretch: 0.4,
      hypertrophyPotential: 0.7,
      frequencySuitability: 0.88,
      progressionPotential: 0.68,
    },
    hanging_leg_raise: {
      evidenceLevel: EVIDENCE,
      stimulus: { abs: 0.72, forearms: 0.14, lats: 0.08, biceps: 0.06 },
      fatigue: 0.38,
      recoveryDemand: 0.32,
      jointStress: { lumbarStress: 0.28, hipStress: 0.22, shoulderStress: 0.24, elbowStress: 0.18, wristStress: 0.2 },
      skillRequirement: 0.45,
      mobilityRequirement: 0.38,
      stabilityRequirement: 0.48,
      loadedStretch: 0.35,
      hypertrophyPotential: 0.72,
      frequencySuitability: 0.8,
      progressionPotential: 0.62,
    },
    ab_wheel_rollout: {
      evidenceLevel: EVIDENCE,
      stimulus: { abs: 0.62, lats: 0.14, triceps: 0.12, frontDelts: 0.12 },
      fatigue: 0.36,
      recoveryDemand: 0.3,
      jointStress: { lumbarStress: 0.42, shoulderStress: 0.32, elbowStress: 0.22, wristStress: 0.18 },
      skillRequirement: 0.52,
      mobilityRequirement: 0.4,
      stabilityRequirement: 0.55,
      loadedStretch: 0.38,
      hypertrophyPotential: 0.68,
      frequencySuitability: 0.76,
      progressionPotential: 0.58,
    },
    plank: {
      evidenceLevel: EVIDENCE,
      stimulus: { abs: 0.55, upperBack: 0.2, glutes: 0.12, frontDelts: 0.08, sideDelts: 0.05 },
      fatigue: 0.22,
      recoveryDemand: 0.18,
      jointStress: { lumbarStress: 0.22, shoulderStress: 0.18, hipStress: 0.1, elbowStress: 0.08 },
      skillRequirement: 0.15,
      mobilityRequirement: 0.12,
      stabilityRequirement: 0.35,
      loadedStretch: 0.15,
      hypertrophyPotential: 0.55,
      frequencySuitability: 0.88,
      progressionPotential: 0.52,
    },
    ...HYPERTROPHY_CORE_V1_PHASE6_SEEDS,
  });
