// lib/data/program/programDayWorkoutTypes.ts
/**
 * Types for the Program Builder weekly-split DAY view.
 *
 * The exercise engine generates structure (slots per muscle group with sets/intensity/day), then a
 * pure assignment step distributes those slots across the program's training days. A
 * {@link ProgramDayWorkout} is the per-day projection used by the Weekly Split card and the day
 * workout page. Pure data only — no IO, no React, no Firebase/API.
 */
import type { ProgramExerciseSlot } from "@/lib/data/program/programExerciseRecommendationTypes";

/** Resolved training-day assignment for one slot. */
export type SlotDayAssignmentEntry = {
  dayId: string;
  /** "engine" = generated by the balancing algorithm; "manual" = moved by the user. */
  source: "engine" | "manual";
};

/** Map of stable slot id → its resolved training-day assignment. */
export type SlotDayAssignment = Record<string, SlotDayAssignmentEntry>;

/** One slot enriched with its muscle-group label, for rendering on a day workout page. */
export type ProgramDaySlot = ProgramExerciseSlot & {
  /** Human-readable muscle group label (e.g. "Upper Chest"). */
  muscleLabel: string;
};

/** The full workout for one training-split day: its assigned slots + headline totals. */
export type ProgramDayWorkout = {
  /** Stable split day id, e.g. "day-1". */
  dayId: string;
  /** 1-based day position in the split. */
  dayIndex: number;
  /** Display name (custom-aware). */
  name: string;
  /** Sum of working sets across all assigned slots. */
  totalSets: number;
  /** Number of assigned exercise slots (selected or empty). */
  exerciseCount: number;
  /** Slots assigned to this day, in muscle-group then slot order. */
  slots: ProgramDaySlot[];
};

/** A candidate destination day for the "Move to another day" flow. */
export type ProgramDayMoveTarget = {
  dayId: string;
  dayIndex: number;
  name: string;
  /** True for the day the slot currently sits on (shown as the current selection). */
  isCurrent: boolean;
};
