/**
 * Chest classification slice (v1).
 * Each key must exist in EXERCISE_LIBRARY_V1 with `primaryBucket: "Chest"`.
 * Back slice: `classificationsBack.v1.ts`.
 */

import type { ChestExerciseClassificationV1 } from "./classificationTypes";
import { CLASSIFICATION_SCHEMA_VERSION } from "./classificationTypes";

const J = {
  pec: ["shoulder", "elbow"] as const,
  pecScap: ["shoulder", "elbow", "scapulothoracic"] as const,
};

function chestRow(
  row: Omit<ChestExerciseClassificationV1, "schemaVersion" | "categoryKey" | "primaryMuscleGroup">,
): ChestExerciseClassificationV1 {
  return {
    schemaVersion: CLASSIFICATION_SCHEMA_VERSION,
    categoryKey: "chest",
    primaryMuscleGroup: "chest",
    ...row,
  };
}

/**
 * Chest category slice: one row per library exercise with `primaryBucket: "Chest"`.
 * Evidence is library_derived: patterns follow existing names, equipment, and detailed tags.
 */
export const CHEST_CLASSIFICATION_BY_EXERCISE_ID: Readonly<
  Record<string, ChestExerciseClassificationV1>
> = {
  bench_press: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "horizontal_press",
    laterality: "bilateral",
    loadModality: "barbell",
    compoundIsolation: "compound",
    plane: "horizontal",
    preferExistingMuscleContributionMap: true,
    jointsPrimary: J.pec,
  }),
  incline_bench_press: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "incline_press",
    laterality: "bilateral",
    loadModality: "barbell",
    compoundIsolation: "compound",
    plane: "incline",
    preferExistingMuscleContributionMap: true,
    jointsPrimary: J.pec,
  }),
  dumbbell_bench_press: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "horizontal_press",
    laterality: "bilateral",
    loadModality: "dumbbell",
    compoundIsolation: "compound",
    plane: "horizontal",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
  }),
  push_up: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "push_up",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "compound",
    plane: "horizontal",
    preferExistingMuscleContributionMap: true,
    jointsPrimary: J.pec,
  }),
  floor_press: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "floor_press",
    laterality: "bilateral",
    loadModality: "barbell",
    compoundIsolation: "compound",
    plane: "horizontal",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
  }),
  decline_bench_press: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "decline_press",
    laterality: "bilateral",
    loadModality: "barbell",
    compoundIsolation: "compound",
    plane: "decline",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
  }),
  dumbbell_incline_bench_press: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "incline_press",
    laterality: "bilateral",
    loadModality: "dumbbell",
    compoundIsolation: "compound",
    plane: "incline",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
  }),
  dumbbell_decline_bench_press: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "decline_press",
    laterality: "bilateral",
    loadModality: "dumbbell",
    compoundIsolation: "compound",
    plane: "decline",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
  }),
  dumbbell_fly: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "fly_adduction",
    laterality: "bilateral",
    loadModality: "dumbbell",
    compoundIsolation: "isolation",
    plane: "transverse_adduction",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
  }),
  dumbbell_incline_fly: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "fly_adduction",
    laterality: "bilateral",
    loadModality: "dumbbell",
    compoundIsolation: "isolation",
    plane: "incline",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
  }),
  dumbbell_pullover: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "pullover",
    laterality: "bilateral",
    loadModality: "dumbbell",
    compoundIsolation: "isolation",
    plane: "multi",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
    notes: "Library tags chest + lats; classification keeps chest as category with lat co-stimulus.",
  }),
  dumbbell_bench_press_neutral: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "horizontal_press",
    laterality: "bilateral",
    loadModality: "dumbbell",
    compoundIsolation: "compound",
    plane: "horizontal",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
  }),
  dumbbell_chest_fly_flat: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "fly_adduction",
    laterality: "bilateral",
    loadModality: "dumbbell",
    compoundIsolation: "isolation",
    plane: "transverse_adduction",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
  }),
  machine_chest_press: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "horizontal_press",
    laterality: "bilateral",
    loadModality: "machine_selectorized",
    compoundIsolation: "compound",
    plane: "horizontal",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
  }),
  machine_incline_chest_press: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "incline_press",
    laterality: "bilateral",
    loadModality: "machine_selectorized",
    compoundIsolation: "compound",
    plane: "incline",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
  }),
  machine_pec_fly: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "fly_adduction",
    laterality: "bilateral",
    loadModality: "machine_selectorized",
    compoundIsolation: "isolation",
    plane: "transverse_adduction",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
  }),
  machine_cable_crossover_high: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "cable_crossover",
    laterality: "bilateral",
    loadModality: "cable",
    compoundIsolation: "isolation",
    plane: "decline",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
    notes: "High-to-mid line emphasizes lower pec line per library detailed tags.",
  }),
  machine_cable_crossover_low: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "cable_crossover",
    laterality: "bilateral",
    loadModality: "cable",
    compoundIsolation: "isolation",
    plane: "incline",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
    notes: "Low-to-mid line emphasizes upper chest line per library detailed tags.",
  }),
  cable_fly: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "fly_adduction",
    laterality: "bilateral",
    loadModality: "cable",
    compoundIsolation: "isolation",
    plane: "transverse_adduction",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
  }),
  cable_chest_press: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "horizontal_press",
    laterality: "bilateral",
    loadModality: "cable",
    compoundIsolation: "compound",
    plane: "horizontal",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
  }),
  incline_push_up: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "push_up",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "compound",
    plane: "incline",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
  }),
  decline_push_up: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "push_up",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "compound",
    plane: "decline",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
  }),
  kettlebell_floor_press: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "floor_press",
    laterality: "bilateral",
    loadModality: "kettlebell",
    compoundIsolation: "compound",
    plane: "horizontal",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
  }),
  band_chest_press: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "horizontal_press",
    laterality: "bilateral",
    loadModality: "band",
    compoundIsolation: "compound",
    plane: "horizontal",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
  }),
  medicine_ball_chest_pass: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "power_chest_throw",
    laterality: "bilateral",
    loadModality: "medicine_ball",
    compoundIsolation: "compound",
    plane: "horizontal",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
  }),
  pec_stretch: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "mobility_stretch",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "isolation",
    plane: "na",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pecScap,
  }),
  archer_push_up: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "push_up",
    laterality: "unilateral_each_side",
    loadModality: "bodyweight",
    compoundIsolation: "compound",
    plane: "horizontal",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
    notes: "Bilateral exercise with alternating unilateral emphasis; logged as one exerciseId.",
  }),
  barbell_bench_press_narrow: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "horizontal_press",
    laterality: "bilateral",
    loadModality: "barbell",
    compoundIsolation: "compound",
    plane: "horizontal",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
    notes: "Library primaryBucket remains Chest; triceps load is higher than standard bench.",
  }),
  cable_crossover_high_to_low: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "cable_crossover",
    laterality: "bilateral",
    loadModality: "cable",
    compoundIsolation: "isolation",
    plane: "decline",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
  }),
  cable_crossover_low_to_high: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "cable_crossover",
    laterality: "bilateral",
    loadModality: "cable",
    compoundIsolation: "isolation",
    plane: "incline",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
  }),
  machine_chest_fly: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "fly_adduction",
    laterality: "bilateral",
    loadModality: "machine_selectorized",
    compoundIsolation: "isolation",
    plane: "transverse_adduction",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
  }),
  machine_decline_chest_press: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "decline_press",
    laterality: "bilateral",
    loadModality: "machine_selectorized",
    compoundIsolation: "compound",
    plane: "decline",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
  }),
  smith_machine_bench_press: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "horizontal_press",
    laterality: "bilateral",
    loadModality: "machine_smith",
    compoundIsolation: "compound",
    plane: "horizontal",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
  }),
  smith_machine_incline_bench: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "incline_press",
    laterality: "bilateral",
    loadModality: "machine_smith",
    compoundIsolation: "compound",
    plane: "incline",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
  }),
  cable_incline_fly: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "fly_adduction",
    laterality: "bilateral",
    loadModality: "cable",
    compoundIsolation: "isolation",
    plane: "incline",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
  }),
  cable_decline_fly: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "fly_adduction",
    laterality: "bilateral",
    loadModality: "cable",
    compoundIsolation: "isolation",
    plane: "decline",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
  }),
  cable_standing_chest_press: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "horizontal_press",
    laterality: "bilateral",
    loadModality: "cable",
    compoundIsolation: "compound",
    plane: "horizontal",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
  }),
  dumbbell_floor_press: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "floor_press",
    laterality: "bilateral",
    loadModality: "dumbbell",
    compoundIsolation: "compound",
    plane: "horizontal",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
  }),
  dumbbell_hex_press: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "horizontal_press",
    laterality: "bilateral",
    loadModality: "dumbbell",
    compoundIsolation: "compound",
    plane: "horizontal",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
  }),
  dumbbell_pullover_flat: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "pullover",
    laterality: "bilateral",
    loadModality: "dumbbell",
    compoundIsolation: "isolation",
    plane: "multi",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
    notes: "Same dual emphasis as dumbbell_pullover; flat variant in library.",
  }),
  dumbbell_bench_press_alternating: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "horizontal_press",
    laterality: "alternating",
    loadModality: "dumbbell",
    compoundIsolation: "compound",
    plane: "horizontal",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
  }),
  dumbbell_fly_incline: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "fly_adduction",
    laterality: "bilateral",
    loadModality: "dumbbell",
    compoundIsolation: "isolation",
    plane: "incline",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
    notes: "Duplicate naming intent as dumbbell_incline_fly; both remain in catalog.",
  }),
  dumbbell_fly_decline: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "fly_adduction",
    laterality: "bilateral",
    loadModality: "dumbbell",
    compoundIsolation: "isolation",
    plane: "decline",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
  }),
  ring_push_up: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "push_up",
    laterality: "bilateral",
    loadModality: "bodyweight_rings",
    compoundIsolation: "compound",
    plane: "horizontal",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
  }),
  ring_fly: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "fly_adduction",
    laterality: "bilateral",
    loadModality: "bodyweight_rings",
    compoundIsolation: "isolation",
    plane: "transverse_adduction",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
  }),
  pseudo_planche_push_up: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "push_up",
    secondaryPatterns: ["incline_press"],
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "mixed",
    plane: "multi",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
    notes: "Library lists substantial anterior delt with chest; mixed compound.",
  }),
  wide_push_up: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "push_up",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "compound",
    plane: "horizontal",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
  }),
  cable_chest_fly_high: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "cable_crossover",
    laterality: "bilateral",
    loadModality: "cable",
    compoundIsolation: "isolation",
    plane: "decline",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
  }),
  cable_chest_fly_low: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "cable_crossover",
    laterality: "bilateral",
    loadModality: "cable",
    compoundIsolation: "isolation",
    plane: "incline",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
  }),
  cable_incline_chest_fly: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "fly_adduction",
    laterality: "bilateral",
    loadModality: "cable",
    compoundIsolation: "isolation",
    plane: "incline",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
  }),
  machine_chest_press_vertical: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "horizontal_press",
    laterality: "bilateral",
    loadModality: "machine_selectorized",
    compoundIsolation: "compound",
    plane: "multi",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
    notes: "Vertical stack path; still catalogued as chest press.",
  }),
  resistance_band_chest_fly: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "fly_adduction",
    laterality: "bilateral",
    loadModality: "band",
    compoundIsolation: "isolation",
    plane: "transverse_adduction",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
  }),
  band_chest_fly: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "fly_adduction",
    laterality: "bilateral",
    loadModality: "band",
    compoundIsolation: "isolation",
    plane: "transverse_adduction",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
  }),
  band_standing_chest_press: chestRow({
    evidenceLevel: "library_derived",
    primaryPattern: "horizontal_press",
    laterality: "bilateral",
    loadModality: "band",
    compoundIsolation: "compound",
    plane: "horizontal",
    preferExistingMuscleContributionMap: false,
    jointsPrimary: J.pec,
  }),
};

export function listChestClassificationExerciseIds(): readonly string[] {
  return Object.keys(CHEST_CLASSIFICATION_BY_EXERCISE_ID).sort((a, b) => a.localeCompare(b));
}
