/**
 * Core classification slice (v1).
 * One row per `EXERCISE_LIBRARY_V1` entry with `primaryBucket: "Core"`.
 */

import type { CoreExerciseClassificationV1 } from "./classificationTypes";
import { CLASSIFICATION_SCHEMA_VERSION } from "./classificationTypes";

const PREFER_MUSCLE_CONTRIBUTION_MAP = new Set(["plank", "hanging_leg_raise"]);

const J = {
  spineHip: ["spine", "hip"] as const,
  spineHipShoulder: ["spine", "hip", "shoulder"] as const,
  spineShoulder: ["spine", "shoulder"] as const,
};

function coreRow(
  exerciseId: string,
  row: Omit<
    CoreExerciseClassificationV1,
    "schemaVersion" | "categoryKey" | "primaryMuscleGroup" | "preferExistingMuscleContributionMap"
  >,
): [string, CoreExerciseClassificationV1] {
  return [
    exerciseId,
    {
      schemaVersion: CLASSIFICATION_SCHEMA_VERSION,
      categoryKey: "core",
      primaryMuscleGroup: "core",
      ...row,
      preferExistingMuscleContributionMap: PREFER_MUSCLE_CONTRIBUTION_MAP.has(exerciseId),
    },
  ];
}

function bulkCore(
  ids: readonly string[],
  row: Omit<
    CoreExerciseClassificationV1,
    "schemaVersion" | "categoryKey" | "primaryMuscleGroup" | "preferExistingMuscleContributionMap" | "notes"
  > & { notes?: string },
): [string, CoreExerciseClassificationV1][] {
  return ids.map((id) => coreRow(id, row));
}

const ENTRIES: [string, CoreExerciseClassificationV1][] = [
  coreRow("plank", {
    evidenceLevel: "library_derived",
    primaryPattern: "trunk_stability_hold",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.spineHip,
  }),
  coreRow("weighted_plank", {
    evidenceLevel: "library_derived",
    primaryPattern: "trunk_stability_hold",
    laterality: "bilateral",
    loadModality: "other",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.spineHip,
  }),
  coreRow("ring_plank", {
    evidenceLevel: "library_derived",
    primaryPattern: "trunk_stability_hold",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "compound",
    plane: "multi",
    jointsPrimary: J.spineHipShoulder,
  }),
  coreRow("side_plank", {
    evidenceLevel: "library_derived",
    primaryPattern: "anti_lateral_flexion",
    laterality: "unilateral_each_side",
    loadModality: "bodyweight",
    compoundIsolation: "compound",
    plane: "frontal",
    jointsPrimary: J.spineHipShoulder,
  }),
  ...bulkCore(["hollow_hold", "hollow_body_hold"], {
    evidenceLevel: "library_derived",
    primaryPattern: "hollow_body_hold",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.spineHip,
  }),
  ...bulkCore(["l_sit_hold", "ring_l_sit", "tuck_hold"], {
    evidenceLevel: "library_derived",
    primaryPattern: "gymnastics_compression_hold",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "compound",
    plane: "multi",
    jointsPrimary: J.spineHip,
  }),
  coreRow("hanging_leg_raise", {
    evidenceLevel: "library_derived",
    primaryPattern: "hip_flexion_emphasis_core",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.spineHipShoulder,
  }),
  coreRow("weighted_leg_raise", {
    evidenceLevel: "library_derived",
    primaryPattern: "hip_flexion_emphasis_core",
    laterality: "bilateral",
    loadModality: "other",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.spineHip,
  }),
  ...bulkCore(["flutter_kick", "scissor_kick"], {
    evidenceLevel: "library_derived",
    primaryPattern: "hip_flexion_emphasis_core",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "isolation",
    plane: "sagittal",
    jointsPrimary: J.spineHip,
  }),
  coreRow("mountain_climber", {
    evidenceLevel: "library_derived",
    primaryPattern: "conditioning_core_mixed",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "mixed",
    plane: "multi",
    jointsPrimary: J.spineHipShoulder,
  }),
  coreRow("cable_crunch", {
    evidenceLevel: "library_derived",
    primaryPattern: "trunk_flexion",
    laterality: "bilateral",
    loadModality: "cable",
    compoundIsolation: "isolation",
    plane: "sagittal",
    jointsPrimary: J.spineHip,
  }),
  coreRow("band_crunch", {
    evidenceLevel: "library_derived",
    primaryPattern: "trunk_flexion",
    laterality: "bilateral",
    loadModality: "band",
    compoundIsolation: "isolation",
    plane: "sagittal",
    jointsPrimary: J.spineHip,
  }),
  coreRow("band_crunch_standing", {
    evidenceLevel: "library_derived",
    primaryPattern: "trunk_flexion",
    laterality: "bilateral",
    loadModality: "band",
    compoundIsolation: "isolation",
    plane: "sagittal",
    jointsPrimary: J.spineHip,
  }),
  coreRow("bicycle_crunch", {
    evidenceLevel: "library_derived",
    primaryPattern: "trunk_flexion",
    laterality: "alternating",
    loadModality: "bodyweight",
    compoundIsolation: "isolation",
    plane: "multi",
    jointsPrimary: J.spineHip,
  }),
  coreRow("reverse_crunch", {
    evidenceLevel: "library_derived",
    primaryPattern: "trunk_flexion",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "isolation",
    plane: "sagittal",
    jointsPrimary: J.spineHip,
  }),
  coreRow("weighted_crunch", {
    evidenceLevel: "library_derived",
    primaryPattern: "trunk_flexion",
    laterality: "bilateral",
    loadModality: "other",
    compoundIsolation: "isolation",
    plane: "sagittal",
    jointsPrimary: J.spineHip,
  }),
  coreRow("weighted_sit_up", {
    evidenceLevel: "library_derived",
    primaryPattern: "trunk_flexion",
    laterality: "bilateral",
    loadModality: "other",
    compoundIsolation: "isolation",
    plane: "sagittal",
    jointsPrimary: J.spineHip,
  }),
  coreRow("v_up", {
    evidenceLevel: "library_derived",
    primaryPattern: "trunk_flexion",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.spineHip,
  }),
  coreRow("medicine_ball_v_up", {
    evidenceLevel: "library_derived",
    primaryPattern: "trunk_flexion",
    laterality: "bilateral",
    loadModality: "medicine_ball",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.spineHip,
  }),
  coreRow("dead_bug", {
    evidenceLevel: "library_derived",
    primaryPattern: "trunk_stability_hold",
    laterality: "alternating",
    loadModality: "bodyweight",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.spineHip,
  }),
  coreRow("band_deadbug", {
    evidenceLevel: "library_derived",
    primaryPattern: "trunk_stability_hold",
    laterality: "alternating",
    loadModality: "band",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.spineHip,
  }),
  coreRow("bird_dog", {
    evidenceLevel: "library_derived",
    primaryPattern: "trunk_stability_hold",
    laterality: "alternating",
    loadModality: "bodyweight",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.spineHipShoulder,
  }),
  coreRow("ab_wheel_rollout", {
    evidenceLevel: "library_derived",
    primaryPattern: "anti_extension_rollout",
    laterality: "bilateral",
    loadModality: "other",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.spineShoulder,
  }),
  coreRow("barbell_rollout", {
    evidenceLevel: "library_derived",
    primaryPattern: "anti_extension_rollout",
    laterality: "bilateral",
    loadModality: "barbell",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.spineShoulder,
  }),
  coreRow("pallof_press", {
    evidenceLevel: "library_derived",
    primaryPattern: "anti_rotation",
    laterality: "bilateral",
    loadModality: "band",
    compoundIsolation: "compound",
    plane: "transverse",
    jointsPrimary: J.spineHipShoulder,
  }),
  coreRow("band_anti_rotation_hold", {
    evidenceLevel: "library_derived",
    primaryPattern: "anti_rotation",
    laterality: "bilateral",
    loadModality: "band",
    compoundIsolation: "compound",
    plane: "transverse",
    jointsPrimary: J.spineHip,
  }),
  coreRow("dumbbell_side_bend", {
    evidenceLevel: "library_derived",
    primaryPattern: "lateral_trunk_flexion",
    laterality: "unilateral_each_side",
    loadModality: "dumbbell",
    compoundIsolation: "isolation",
    plane: "frontal",
    jointsPrimary: J.spineHip,
  }),
  coreRow("dumbbell_suitcase_carry", {
    evidenceLevel: "library_derived",
    primaryPattern: "loaded_carry_core",
    laterality: "unilateral_each_side",
    loadModality: "dumbbell",
    compoundIsolation: "compound",
    plane: "frontal",
    jointsPrimary: J.spineHip,
  }),
  coreRow("kettlebell_suitcase_carry", {
    evidenceLevel: "library_derived",
    primaryPattern: "loaded_carry_core",
    laterality: "unilateral_each_side",
    loadModality: "kettlebell",
    compoundIsolation: "compound",
    plane: "frontal",
    jointsPrimary: J.spineHip,
  }),
  coreRow("dumbbell_woodchop", {
    evidenceLevel: "library_derived",
    primaryPattern: "trunk_rotation",
    laterality: "bilateral",
    loadModality: "dumbbell",
    compoundIsolation: "compound",
    plane: "multi",
    jointsPrimary: J.spineHipShoulder,
  }),
  coreRow("cable_woodchop", {
    evidenceLevel: "library_derived",
    primaryPattern: "trunk_rotation",
    laterality: "bilateral",
    loadModality: "cable",
    compoundIsolation: "compound",
    plane: "multi",
    jointsPrimary: J.spineHipShoulder,
  }),
  coreRow("band_woodchop", {
    evidenceLevel: "library_derived",
    primaryPattern: "trunk_rotation",
    laterality: "bilateral",
    loadModality: "band",
    compoundIsolation: "compound",
    plane: "multi",
    jointsPrimary: J.spineHipShoulder,
  }),
  coreRow("band_woodchop_high", {
    evidenceLevel: "library_derived",
    primaryPattern: "trunk_rotation",
    laterality: "bilateral",
    loadModality: "band",
    compoundIsolation: "compound",
    plane: "multi",
    jointsPrimary: J.spineHipShoulder,
  }),
  coreRow("band_woodchop_low", {
    evidenceLevel: "library_derived",
    primaryPattern: "trunk_rotation",
    laterality: "bilateral",
    loadModality: "band",
    compoundIsolation: "compound",
    plane: "multi",
    jointsPrimary: J.spineHipShoulder,
  }),
  coreRow("medicine_ball_woodchop", {
    evidenceLevel: "library_derived",
    primaryPattern: "trunk_rotation",
    laterality: "bilateral",
    loadModality: "medicine_ball",
    compoundIsolation: "compound",
    plane: "multi",
    jointsPrimary: J.spineHipShoulder,
  }),
  coreRow("kettlebell_figure_eight", {
    evidenceLevel: "library_derived",
    primaryPattern: "trunk_rotation",
    laterality: "bilateral",
    loadModality: "kettlebell",
    compoundIsolation: "compound",
    plane: "multi",
    jointsPrimary: J.spineHipShoulder,
  }),
  coreRow("band_rotational_chopp", {
    evidenceLevel: "library_derived",
    primaryPattern: "trunk_rotation",
    laterality: "bilateral",
    loadModality: "band",
    compoundIsolation: "compound",
    plane: "multi",
    jointsPrimary: J.spineHipShoulder,
  }),
  coreRow("band_lateral_chopp", {
    evidenceLevel: "library_derived",
    primaryPattern: "trunk_rotation",
    laterality: "bilateral",
    loadModality: "band",
    compoundIsolation: "compound",
    plane: "multi",
    jointsPrimary: J.spineHipShoulder,
  }),
  coreRow("band_standing_rotation", {
    evidenceLevel: "library_derived",
    primaryPattern: "trunk_rotation",
    laterality: "bilateral",
    loadModality: "band",
    compoundIsolation: "compound",
    plane: "transverse",
    jointsPrimary: J.spineHip,
  }),
  coreRow("resisted_hip_rotation", {
    evidenceLevel: "library_derived",
    primaryPattern: "trunk_rotation",
    laterality: "bilateral",
    loadModality: "band",
    compoundIsolation: "compound",
    plane: "transverse",
    jointsPrimary: J.spineHip,
  }),
  coreRow("medicine_ball_russian_twist", {
    evidenceLevel: "library_derived",
    primaryPattern: "trunk_rotation",
    laterality: "alternating",
    loadModality: "medicine_ball",
    compoundIsolation: "compound",
    plane: "transverse",
    jointsPrimary: J.spineHip,
  }),
  coreRow("torso_twist", {
    evidenceLevel: "library_derived",
    primaryPattern: "trunk_rotation",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "mixed",
    plane: "transverse",
    jointsPrimary: J.spineHip,
  }),
  coreRow("yoga_triangle", {
    evidenceLevel: "library_derived",
    primaryPattern: "trunk_rotation",
    laterality: "unilateral_each_side",
    loadModality: "bodyweight",
    compoundIsolation: "mixed",
    plane: "multi",
    jointsPrimary: J.spineHip,
  }),
  coreRow("medicine_ball_rotational_throw", {
    evidenceLevel: "library_derived",
    primaryPattern: "rotational_power_throw",
    laterality: "bilateral",
    loadModality: "medicine_ball",
    compoundIsolation: "mixed",
    plane: "transverse",
    jointsPrimary: J.spineHipShoulder,
  }),
  ...bulkCore(["cat_cow", "yoga_cat_cow", "quadruped_rockback", "sphinx_hold", "toe_touch"], {
    evidenceLevel: "library_derived",
    primaryPattern: "spinal_mobility_trunk",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "mixed",
    plane: "sagittal",
    jointsPrimary: J.spineHip,
    notes: "Toe touch includes posterior-chain mobility; catalog bucket remains Core.",
  }),
];

export const CORE_CLASSIFICATION_BY_EXERCISE_ID: Readonly<Record<string, CoreExerciseClassificationV1>> =
  Object.fromEntries(ENTRIES);

export function listCoreClassificationExerciseIds(): readonly string[] {
  return Object.keys(CORE_CLASSIFICATION_BY_EXERCISE_ID).sort((a, b) => a.localeCompare(b));
}
