/**
 * Lower-body classification slices (v1).
 * Membership rules: `lowerBodySliceRules.ts` + `PRODUCT_RULES_LOWER_BODY_CLASSIFICATION.md`.
 */

import type {
  CalvesExerciseClassificationV1,
  GlutesExerciseClassificationV1,
  HamstringsExerciseClassificationV1,
  QuadsExerciseClassificationV1,
} from "./classificationTypes";
import { CLASSIFICATION_SCHEMA_VERSION } from "./classificationTypes";

const PREFER_MUSCLE_CONTRIBUTION_MAP = new Set([
  "squat",
  "leg_press",
  "leg_extension",
  "romanian_deadlift",
  "leg_curl",
  "hip_thrust",
  "calf_raise",
]);

const J = {
  hipKnee: ["hip", "knee"] as const,
  kneeHip: ["knee", "hip"] as const,
  ankleKnee: ["ankle", "knee"] as const,
  hipSpineKnee: ["hip", "spine", "knee"] as const,
  hip: ["hip"] as const,
  hipKneeShoulder: ["hip", "knee", "shoulder"] as const,
};

function quadsRow(
  exerciseId: string,
  row: Omit<
    QuadsExerciseClassificationV1,
    "schemaVersion" | "categoryKey" | "primaryMuscleGroup" | "preferExistingMuscleContributionMap"
  >,
): [string, QuadsExerciseClassificationV1] {
  return [
    exerciseId,
    {
      schemaVersion: CLASSIFICATION_SCHEMA_VERSION,
      categoryKey: "quads",
      primaryMuscleGroup: "quads",
      ...row,
      preferExistingMuscleContributionMap: PREFER_MUSCLE_CONTRIBUTION_MAP.has(exerciseId),
    },
  ];
}

function hamstringsRow(
  exerciseId: string,
  row: Omit<
    HamstringsExerciseClassificationV1,
    "schemaVersion" | "categoryKey" | "primaryMuscleGroup" | "preferExistingMuscleContributionMap"
  >,
): [string, HamstringsExerciseClassificationV1] {
  return [
    exerciseId,
    {
      schemaVersion: CLASSIFICATION_SCHEMA_VERSION,
      categoryKey: "hamstrings",
      primaryMuscleGroup: "hamstrings",
      ...row,
      preferExistingMuscleContributionMap: PREFER_MUSCLE_CONTRIBUTION_MAP.has(exerciseId),
    },
  ];
}

function glutesRow(
  exerciseId: string,
  row: Omit<
    GlutesExerciseClassificationV1,
    "schemaVersion" | "categoryKey" | "primaryMuscleGroup" | "preferExistingMuscleContributionMap"
  >,
): [string, GlutesExerciseClassificationV1] {
  return [
    exerciseId,
    {
      schemaVersion: CLASSIFICATION_SCHEMA_VERSION,
      categoryKey: "glutes",
      primaryMuscleGroup: "glutes",
      ...row,
      preferExistingMuscleContributionMap: PREFER_MUSCLE_CONTRIBUTION_MAP.has(exerciseId),
    },
  ];
}

function calvesRow(
  exerciseId: string,
  row: Omit<
    CalvesExerciseClassificationV1,
    "schemaVersion" | "categoryKey" | "primaryMuscleGroup" | "preferExistingMuscleContributionMap"
  >,
): [string, CalvesExerciseClassificationV1] {
  return [
    exerciseId,
    {
      schemaVersion: CLASSIFICATION_SCHEMA_VERSION,
      categoryKey: "calves",
      primaryMuscleGroup: "calves",
      ...row,
      preferExistingMuscleContributionMap: PREFER_MUSCLE_CONTRIBUTION_MAP.has(exerciseId),
    },
  ];
}

const QUADS_ENTRIES: [string, QuadsExerciseClassificationV1][] = [
  quadsRow("band_goblet_squat", {
    evidenceLevel: "library_derived",
    primaryPattern: "squat_pattern",
    laterality: "bilateral",
    loadModality: "band",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("band_leg_extension", {
    evidenceLevel: "library_derived",
    primaryPattern: "knee_extension_isolation",
    laterality: "bilateral",
    loadModality: "band",
    compoundIsolation: "isolation",
    plane: "sagittal",
    jointsPrimary: J.kneeHip,
  }),
  quadsRow("band_lunge", {
    evidenceLevel: "library_derived",
    primaryPattern: "lunge_pattern",
    laterality: "bilateral",
    loadModality: "band",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("band_squat", {
    evidenceLevel: "library_derived",
    primaryPattern: "squat_pattern",
    laterality: "bilateral",
    loadModality: "band",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("banded_squat", {
    evidenceLevel: "library_derived",
    primaryPattern: "squat_pattern",
    laterality: "bilateral",
    loadModality: "band",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("barbell_lunge", {
    evidenceLevel: "library_derived",
    primaryPattern: "lunge_pattern",
    laterality: "bilateral",
    loadModality: "barbell",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("barbell_walking_lunge", {
    evidenceLevel: "library_derived",
    primaryPattern: "lunge_pattern",
    laterality: "bilateral",
    loadModality: "barbell",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("belt_squat", {
    evidenceLevel: "library_derived",
    primaryPattern: "squat_pattern",
    laterality: "bilateral",
    loadModality: "machine_selectorized",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("bodyweight_lunge", {
    evidenceLevel: "library_derived",
    primaryPattern: "lunge_pattern",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("bodyweight_reverse_lunge", {
    evidenceLevel: "library_derived",
    primaryPattern: "lunge_pattern",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("bodyweight_squat", {
    evidenceLevel: "library_derived",
    primaryPattern: "squat_pattern",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("box_jump", {
    evidenceLevel: "library_derived",
    primaryPattern: "squat_pattern",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("box_squat", {
    evidenceLevel: "library_derived",
    primaryPattern: "squat_pattern",
    laterality: "bilateral",
    loadModality: "barbell",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("bulgarian_split_squat_barbell", {
    evidenceLevel: "library_derived",
    primaryPattern: "lunge_pattern",
    laterality: "bilateral",
    loadModality: "barbell",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("bulgarian_split_squat_dumbbell", {
    evidenceLevel: "library_derived",
    primaryPattern: "lunge_pattern",
    laterality: "bilateral",
    loadModality: "dumbbell",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("cable_leg_extension", {
    evidenceLevel: "library_derived",
    primaryPattern: "knee_extension_isolation",
    laterality: "bilateral",
    loadModality: "cable",
    compoundIsolation: "isolation",
    plane: "sagittal",
    jointsPrimary: J.kneeHip,
  }),
  quadsRow("cossack_squat", {
    evidenceLevel: "library_derived",
    primaryPattern: "squat_pattern",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "mixed",
    plane: "multi",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("dumbbell_goblet_squat", {
    evidenceLevel: "library_derived",
    primaryPattern: "squat_pattern",
    laterality: "bilateral",
    loadModality: "dumbbell",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("dumbbell_lunge", {
    evidenceLevel: "library_derived",
    primaryPattern: "lunge_pattern",
    laterality: "bilateral",
    loadModality: "dumbbell",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("dumbbell_reverse_lunge", {
    evidenceLevel: "library_derived",
    primaryPattern: "lunge_pattern",
    laterality: "bilateral",
    loadModality: "dumbbell",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("dumbbell_squat", {
    evidenceLevel: "library_derived",
    primaryPattern: "squat_pattern",
    laterality: "bilateral",
    loadModality: "dumbbell",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("dumbbell_step_up", {
    evidenceLevel: "library_derived",
    primaryPattern: "lunge_pattern",
    laterality: "bilateral",
    loadModality: "dumbbell",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("dumbbell_step_up_lateral", {
    evidenceLevel: "library_derived",
    primaryPattern: "lunge_pattern",
    laterality: "bilateral",
    loadModality: "dumbbell",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("front_squat", {
    evidenceLevel: "library_derived",
    primaryPattern: "squat_pattern",
    laterality: "bilateral",
    loadModality: "barbell",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("hack_squat", {
    evidenceLevel: "library_derived",
    primaryPattern: "squat_pattern",
    laterality: "bilateral",
    loadModality: "machine_selectorized",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("jump_squat", {
    evidenceLevel: "library_derived",
    primaryPattern: "squat_pattern",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("kettlebell_goblet_squat", {
    evidenceLevel: "library_derived",
    primaryPattern: "squat_pattern",
    laterality: "bilateral",
    loadModality: "kettlebell",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("kettlebell_lunge", {
    evidenceLevel: "library_derived",
    primaryPattern: "lunge_pattern",
    laterality: "bilateral",
    loadModality: "kettlebell",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("kettlebell_sumo_squat", {
    evidenceLevel: "library_derived",
    primaryPattern: "squat_pattern",
    laterality: "bilateral",
    loadModality: "kettlebell",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("lateral_lunge", {
    evidenceLevel: "library_derived",
    primaryPattern: "lunge_pattern",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "compound",
    plane: "multi",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("lateral_shuffle", {
    evidenceLevel: "library_derived",
    primaryPattern: "conditioning_gait_quads",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "mixed",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("leg_extension", {
    evidenceLevel: "library_derived",
    primaryPattern: "knee_extension_isolation",
    laterality: "bilateral",
    loadModality: "machine_selectorized",
    compoundIsolation: "isolation",
    plane: "sagittal",
    jointsPrimary: J.kneeHip,
  }),
  quadsRow("leg_press", {
    evidenceLevel: "library_derived",
    primaryPattern: "leg_press_pattern",
    laterality: "bilateral",
    loadModality: "machine_selectorized",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("machine_leg_extension", {
    evidenceLevel: "library_derived",
    primaryPattern: "knee_extension_isolation",
    laterality: "bilateral",
    loadModality: "machine_selectorized",
    compoundIsolation: "isolation",
    plane: "sagittal",
    jointsPrimary: J.kneeHip,
  }),
  quadsRow("machine_leg_press_vertical", {
    evidenceLevel: "library_derived",
    primaryPattern: "leg_press_pattern",
    laterality: "bilateral",
    loadModality: "machine_selectorized",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("medicine_ball_squat", {
    evidenceLevel: "library_derived",
    primaryPattern: "squat_pattern",
    laterality: "bilateral",
    loadModality: "medicine_ball",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("overhead_squat", {
    evidenceLevel: "library_derived",
    primaryPattern: "squat_pattern",
    laterality: "bilateral",
    loadModality: "barbell",
    compoundIsolation: "compound",
    plane: "multi",
    jointsPrimary: J.hipKneeShoulder,
  }),
  quadsRow("pause_squat", {
    evidenceLevel: "library_derived",
    primaryPattern: "squat_pattern",
    laterality: "bilateral",
    loadModality: "barbell",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("pistol_squat", {
    evidenceLevel: "library_derived",
    primaryPattern: "squat_pattern",
    laterality: "unilateral_each_side",
    loadModality: "bodyweight",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("quad_stretch", {
    evidenceLevel: "library_derived",
    primaryPattern: "mobility_stretch_quad",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "mixed",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("reverse_lunge_barbell", {
    evidenceLevel: "library_derived",
    primaryPattern: "lunge_pattern",
    laterality: "bilateral",
    loadModality: "barbell",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("safety_bar_squat", {
    evidenceLevel: "library_derived",
    primaryPattern: "squat_pattern",
    laterality: "bilateral",
    loadModality: "barbell",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("shrimp_squat", {
    evidenceLevel: "library_derived",
    primaryPattern: "lunge_pattern",
    laterality: "unilateral_each_side",
    loadModality: "bodyweight",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("sissy_squat", {
    evidenceLevel: "library_derived",
    primaryPattern: "squat_pattern",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "isolation",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("skater_jump", {
    evidenceLevel: "library_derived",
    primaryPattern: "lunge_pattern",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("sled_push", {
    evidenceLevel: "library_derived",
    primaryPattern: "sled_push_pattern",
    laterality: "bilateral",
    loadModality: "other",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("smith_machine_squat", {
    evidenceLevel: "library_derived",
    primaryPattern: "squat_pattern",
    laterality: "bilateral",
    loadModality: "machine_smith",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("split_squat_barbell", {
    evidenceLevel: "library_derived",
    primaryPattern: "lunge_pattern",
    laterality: "bilateral",
    loadModality: "barbell",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("split_squat_dumbbell", {
    evidenceLevel: "library_derived",
    primaryPattern: "lunge_pattern",
    laterality: "bilateral",
    loadModality: "dumbbell",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("squat", {
    evidenceLevel: "library_derived",
    primaryPattern: "squat_pattern",
    laterality: "bilateral",
    loadModality: "barbell",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("stair_climber", {
    evidenceLevel: "library_derived",
    primaryPattern: "lunge_pattern",
    laterality: "bilateral",
    loadModality: "other",
    compoundIsolation: "mixed",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("stationary_bike", {
    evidenceLevel: "library_derived",
    primaryPattern: "cardio_cycling_quads",
    laterality: "bilateral",
    loadModality: "other",
    compoundIsolation: "mixed",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("step_up_bodyweight", {
    evidenceLevel: "library_derived",
    primaryPattern: "lunge_pattern",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("sumo_squat_bodyweight", {
    evidenceLevel: "library_derived",
    primaryPattern: "squat_pattern",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("v_squat", {
    evidenceLevel: "library_derived",
    primaryPattern: "squat_pattern",
    laterality: "bilateral",
    loadModality: "machine_selectorized",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("walking_lunge_stretch", {
    evidenceLevel: "library_derived",
    primaryPattern: "lunge_pattern",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "mixed",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("wall_sit", {
    evidenceLevel: "library_derived",
    primaryPattern: "squat_pattern",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("yoga_warrior_one", {
    evidenceLevel: "library_derived",
    primaryPattern: "lunge_pattern",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "mixed",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("yoga_warrior_two", {
    evidenceLevel: "library_derived",
    primaryPattern: "lunge_pattern",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "mixed",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  quadsRow("zercher_squat", {
    evidenceLevel: "library_derived",
    primaryPattern: "squat_pattern",
    laterality: "bilateral",
    loadModality: "barbell",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),

];

const HAMSTRINGS_ENTRIES: [string, HamstringsExerciseClassificationV1][] = [
  hamstringsRow("band_leg_curl", {
    evidenceLevel: "library_derived",
    primaryPattern: "knee_flexion_curl",
    laterality: "bilateral",
    loadModality: "band",
    compoundIsolation: "isolation",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  hamstringsRow("cable_leg_curl", {
    evidenceLevel: "library_derived",
    primaryPattern: "knee_flexion_curl",
    laterality: "bilateral",
    loadModality: "cable",
    compoundIsolation: "isolation",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  hamstringsRow("ghr", {
    evidenceLevel: "library_derived",
    primaryPattern: "glute_ham_raise_pattern",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  hamstringsRow("glute_hammer_swing", {
    evidenceLevel: "library_derived",
    primaryPattern: "hip_hinge_posterior",
    laterality: "bilateral",
    loadModality: "machine_selectorized",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipSpineKnee,
  }),
  hamstringsRow("hamstring_stretch", {
    evidenceLevel: "library_derived",
    primaryPattern: "mobility_stretch_hamstring",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "mixed",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  hamstringsRow("leg_curl", {
    evidenceLevel: "library_derived",
    primaryPattern: "knee_flexion_curl",
    laterality: "bilateral",
    loadModality: "machine_selectorized",
    compoundIsolation: "isolation",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  hamstringsRow("machine_leg_curl_lying", {
    evidenceLevel: "library_derived",
    primaryPattern: "knee_flexion_curl",
    laterality: "bilateral",
    loadModality: "machine_selectorized",
    compoundIsolation: "isolation",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  hamstringsRow("machine_leg_curl_seated", {
    evidenceLevel: "library_derived",
    primaryPattern: "knee_flexion_curl",
    laterality: "bilateral",
    loadModality: "machine_selectorized",
    compoundIsolation: "isolation",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  hamstringsRow("nordic_curl", {
    evidenceLevel: "library_derived",
    primaryPattern: "nordic_knee_flexion",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  hamstringsRow("seated_leg_curl_machine", {
    evidenceLevel: "library_derived",
    primaryPattern: "knee_flexion_curl",
    laterality: "bilateral",
    loadModality: "machine_selectorized",
    compoundIsolation: "isolation",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),

  hamstringsRow("band_romanian_deadlift", {
    evidenceLevel: "library_derived",
    primaryPattern: "hip_hinge_posterior",
    laterality: "bilateral",
    loadModality: "band",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipSpineKnee,
  }),
  hamstringsRow("dumbbell_romanian_deadlift", {
    evidenceLevel: "library_derived",
    primaryPattern: "hip_hinge_posterior",
    laterality: "bilateral",
    loadModality: "dumbbell",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipSpineKnee,
  }),
  hamstringsRow("dumbbell_stiff_leg_deadlift", {
    evidenceLevel: "library_derived",
    primaryPattern: "hip_hinge_posterior",
    laterality: "bilateral",
    loadModality: "dumbbell",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipSpineKnee,
  }),
  hamstringsRow("kettlebell_romanian_deadlift", {
    evidenceLevel: "library_derived",
    primaryPattern: "hip_hinge_posterior",
    laterality: "bilateral",
    loadModality: "kettlebell",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipSpineKnee,
  }),
  hamstringsRow("romanian_deadlift", {
    evidenceLevel: "library_derived",
    primaryPattern: "hip_hinge_posterior",
    laterality: "bilateral",
    loadModality: "barbell",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipSpineKnee,
  }),
  hamstringsRow("single_leg_rdl_bodyweight", {
    evidenceLevel: "library_derived",
    primaryPattern: "hip_hinge_posterior",
    laterality: "unilateral_each_side",
    loadModality: "bodyweight",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipSpineKnee,
  }),
  hamstringsRow("stiff_leg_deadlift", {
    evidenceLevel: "library_derived",
    primaryPattern: "hip_hinge_posterior",
    laterality: "bilateral",
    loadModality: "barbell",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipSpineKnee,
  }),
];

const GLUTES_ENTRIES: [string, GlutesExerciseClassificationV1][] = [
  glutesRow("90_90_hip_switch", {
    evidenceLevel: "library_derived",
    primaryPattern: "mobility_stretch_hip",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "mixed",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  glutesRow("band_glute_bridge", {
    evidenceLevel: "library_derived",
    primaryPattern: "hip_thrust_bridge_pattern",
    laterality: "bilateral",
    loadModality: "band",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  glutesRow("band_hip_abduction", {
    evidenceLevel: "library_derived",
    primaryPattern: "hip_abduction",
    laterality: "bilateral",
    loadModality: "band",
    compoundIsolation: "isolation",
    plane: "frontal",
    jointsPrimary: J.hip,
  }),
  glutesRow("band_monster_walk", {
    evidenceLevel: "library_derived",
    primaryPattern: "hip_abduction",
    laterality: "bilateral",
    loadModality: "band",
    compoundIsolation: "compound",
    plane: "frontal",
    jointsPrimary: J.hip,
  }),
  glutesRow("band_standing_abduction", {
    evidenceLevel: "library_derived",
    primaryPattern: "hip_abduction",
    laterality: "bilateral",
    loadModality: "band",
    compoundIsolation: "isolation",
    plane: "frontal",
    jointsPrimary: J.hip,
  }),
  glutesRow("band_standing_adduction", {
    evidenceLevel: "library_derived",
    primaryPattern: "hip_adduction",
    laterality: "bilateral",
    loadModality: "band",
    compoundIsolation: "isolation",
    plane: "frontal",
    jointsPrimary: J.hip,
  }),
  glutesRow("barbell_curtsy_lunge", {
    evidenceLevel: "library_derived",
    primaryPattern: "lunge_glute_bias",
    laterality: "bilateral",
    loadModality: "barbell",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  glutesRow("barbell_glute_bridge", {
    evidenceLevel: "library_derived",
    primaryPattern: "hip_thrust_bridge_pattern",
    laterality: "bilateral",
    loadModality: "barbell",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  glutesRow("barbell_hip_thrust_single_arm", {
    evidenceLevel: "library_derived",
    primaryPattern: "hip_thrust_bridge_pattern",
    laterality: "bilateral",
    loadModality: "barbell",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  glutesRow("barbell_hip_thrust_single_leg", {
    evidenceLevel: "library_derived",
    primaryPattern: "hip_thrust_bridge_pattern",
    laterality: "unilateral_each_side",
    loadModality: "barbell",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  glutesRow("bodyweight_glute_bridge", {
    evidenceLevel: "library_derived",
    primaryPattern: "hip_thrust_bridge_pattern",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  glutesRow("bodyweight_hip_thrust", {
    evidenceLevel: "library_derived",
    primaryPattern: "hip_thrust_bridge_pattern",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  glutesRow("cable_hip_abduction", {
    evidenceLevel: "library_derived",
    primaryPattern: "hip_abduction",
    laterality: "bilateral",
    loadModality: "cable",
    compoundIsolation: "isolation",
    plane: "frontal",
    jointsPrimary: J.hip,
  }),
  glutesRow("clamshell", {
    evidenceLevel: "library_derived",
    primaryPattern: "hip_abduction",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "isolation",
    plane: "frontal",
    jointsPrimary: J.hip,
  }),
  glutesRow("curtsy_lunge", {
    evidenceLevel: "library_derived",
    primaryPattern: "lunge_glute_bias",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  glutesRow("donkey_kick", {
    evidenceLevel: "library_derived",
    primaryPattern: "kickback_extension",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "isolation",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  glutesRow("dumbbell_glute_bridge", {
    evidenceLevel: "library_derived",
    primaryPattern: "hip_thrust_bridge_pattern",
    laterality: "bilateral",
    loadModality: "dumbbell",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  glutesRow("dumbbell_hip_thrust", {
    evidenceLevel: "library_derived",
    primaryPattern: "hip_thrust_bridge_pattern",
    laterality: "bilateral",
    loadModality: "dumbbell",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  glutesRow("figure_four_stretch", {
    evidenceLevel: "library_derived",
    primaryPattern: "mobility_stretch_hip",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "mixed",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  glutesRow("fire_hydrant", {
    evidenceLevel: "library_derived",
    primaryPattern: "hip_abduction",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "isolation",
    plane: "frontal",
    jointsPrimary: J.hip,
  }),
  glutesRow("frog_stretch", {
    evidenceLevel: "library_derived",
    primaryPattern: "mobility_stretch_hip",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "mixed",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  glutesRow("glute_stretch", {
    evidenceLevel: "library_derived",
    primaryPattern: "mobility_stretch_hip",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "mixed",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  glutesRow("hip_circle", {
    evidenceLevel: "library_derived",
    primaryPattern: "mobility_stretch_hip",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "mixed",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  glutesRow("hip_flexor_stretch", {
    evidenceLevel: "library_derived",
    primaryPattern: "mobility_stretch_hip",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "mixed",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  glutesRow("hip_thrust", {
    evidenceLevel: "library_derived",
    primaryPattern: "hip_thrust_bridge_pattern",
    laterality: "bilateral",
    loadModality: "barbell",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  glutesRow("leg_swing", {
    evidenceLevel: "library_derived",
    primaryPattern: "mobility_stretch_hip",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "mixed",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  glutesRow("machine_hip_abduction", {
    evidenceLevel: "library_derived",
    primaryPattern: "hip_abduction",
    laterality: "bilateral",
    loadModality: "machine_selectorized",
    compoundIsolation: "isolation",
    plane: "frontal",
    jointsPrimary: J.hip,
  }),
  glutesRow("machine_hip_adduction", {
    evidenceLevel: "library_derived",
    primaryPattern: "hip_adduction",
    laterality: "bilateral",
    loadModality: "machine_selectorized",
    compoundIsolation: "isolation",
    plane: "frontal",
    jointsPrimary: J.hip,
  }),
  glutesRow("pigeon_pose", {
    evidenceLevel: "library_derived",
    primaryPattern: "mobility_stretch_hip",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "mixed",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  glutesRow("single_leg_glute_bridge", {
    evidenceLevel: "library_derived",
    primaryPattern: "hip_thrust_bridge_pattern",
    laterality: "unilateral_each_side",
    loadModality: "bodyweight",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),
  glutesRow("single_leg_glute_bridge_band", {
    evidenceLevel: "library_derived",
    primaryPattern: "hip_thrust_bridge_pattern",
    laterality: "unilateral_each_side",
    loadModality: "band",
    compoundIsolation: "compound",
    plane: "sagittal",
    jointsPrimary: J.hipKnee,
  }),

];

const CALVES_ENTRIES: [string, CalvesExerciseClassificationV1][] = [
  calvesRow("ankle_mobility", {
    evidenceLevel: "library_derived",
    primaryPattern: "mobility_stretch_calf",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "mixed",
    plane: "sagittal",
    jointsPrimary: J.ankleKnee,
  }),
  calvesRow("band_calf_raise", {
    evidenceLevel: "library_derived",
    primaryPattern: "plantarflexion_standing",
    laterality: "bilateral",
    loadModality: "band",
    compoundIsolation: "isolation",
    plane: "sagittal",
    jointsPrimary: J.ankleKnee,
  }),
  calvesRow("barbell_calf_raise", {
    evidenceLevel: "library_derived",
    primaryPattern: "plantarflexion_standing",
    laterality: "bilateral",
    loadModality: "barbell",
    compoundIsolation: "isolation",
    plane: "sagittal",
    jointsPrimary: J.ankleKnee,
  }),
  calvesRow("cable_standing_calf_raise", {
    evidenceLevel: "library_derived",
    primaryPattern: "plantarflexion_standing",
    laterality: "bilateral",
    loadModality: "cable",
    compoundIsolation: "isolation",
    plane: "sagittal",
    jointsPrimary: J.ankleKnee,
  }),
  calvesRow("calf_raise", {
    evidenceLevel: "library_derived",
    primaryPattern: "plantarflexion_standing",
    laterality: "bilateral",
    loadModality: "machine_selectorized",
    compoundIsolation: "isolation",
    plane: "sagittal",
    jointsPrimary: J.ankleKnee,
  }),
  calvesRow("calf_stretch", {
    evidenceLevel: "library_derived",
    primaryPattern: "mobility_stretch_calf",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "mixed",
    plane: "sagittal",
    jointsPrimary: J.ankleKnee,
  }),
  calvesRow("dumbbell_calf_raise", {
    evidenceLevel: "library_derived",
    primaryPattern: "plantarflexion_standing",
    laterality: "bilateral",
    loadModality: "dumbbell",
    compoundIsolation: "isolation",
    plane: "sagittal",
    jointsPrimary: J.ankleKnee,
  }),
  calvesRow("hack_squat_calf", {
    evidenceLevel: "library_derived",
    primaryPattern: "plantarflexion_standing",
    laterality: "bilateral",
    loadModality: "machine_selectorized",
    compoundIsolation: "isolation",
    plane: "sagittal",
    jointsPrimary: J.ankleKnee,
  }),
  calvesRow("leg_press_calf_raise", {
    evidenceLevel: "library_derived",
    primaryPattern: "plantarflexion_leg_press",
    laterality: "bilateral",
    loadModality: "machine_selectorized",
    compoundIsolation: "isolation",
    plane: "sagittal",
    jointsPrimary: J.ankleKnee,
  }),
  calvesRow("machine_calf_raise_seated", {
    evidenceLevel: "library_derived",
    primaryPattern: "plantarflexion_seated",
    laterality: "bilateral",
    loadModality: "machine_selectorized",
    compoundIsolation: "isolation",
    plane: "sagittal",
    jointsPrimary: J.ankleKnee,
  }),
  calvesRow("machine_calf_raise_standing", {
    evidenceLevel: "library_derived",
    primaryPattern: "plantarflexion_standing",
    laterality: "bilateral",
    loadModality: "machine_selectorized",
    compoundIsolation: "isolation",
    plane: "sagittal",
    jointsPrimary: J.ankleKnee,
  }),
  calvesRow("seated_calf_raise_machine", {
    evidenceLevel: "library_derived",
    primaryPattern: "plantarflexion_seated",
    laterality: "bilateral",
    loadModality: "machine_selectorized",
    compoundIsolation: "isolation",
    plane: "sagittal",
    jointsPrimary: J.ankleKnee,
  }),
  calvesRow("smith_machine_calf_raise", {
    evidenceLevel: "library_derived",
    primaryPattern: "plantarflexion_standing",
    laterality: "bilateral",
    loadModality: "machine_smith",
    compoundIsolation: "isolation",
    plane: "sagittal",
    jointsPrimary: J.ankleKnee,
  }),
  calvesRow("standing_calf_raise_barbell", {
    evidenceLevel: "library_derived",
    primaryPattern: "plantarflexion_standing",
    laterality: "bilateral",
    loadModality: "barbell",
    compoundIsolation: "isolation",
    plane: "sagittal",
    jointsPrimary: J.ankleKnee,
  }),
  calvesRow("tibia_raise", {
    evidenceLevel: "library_derived",
    primaryPattern: "dorsiflexion_tibialis",
    laterality: "bilateral",
    loadModality: "machine_selectorized",
    compoundIsolation: "isolation",
    plane: "sagittal",
    jointsPrimary: J.ankleKnee,
  }),

];

export const QUADS_CLASSIFICATION_BY_EXERCISE_ID: Readonly<Record<string, QuadsExerciseClassificationV1>> =
  Object.fromEntries(QUADS_ENTRIES);

export const HAMSTRINGS_CLASSIFICATION_BY_EXERCISE_ID: Readonly<
  Record<string, HamstringsExerciseClassificationV1>
> = Object.fromEntries(HAMSTRINGS_ENTRIES);

export const GLUTES_CLASSIFICATION_BY_EXERCISE_ID: Readonly<Record<string, GlutesExerciseClassificationV1>> =
  Object.fromEntries(GLUTES_ENTRIES);

export const CALVES_CLASSIFICATION_BY_EXERCISE_ID: Readonly<Record<string, CalvesExerciseClassificationV1>> =
  Object.fromEntries(CALVES_ENTRIES);

export function listQuadsClassificationExerciseIds(): readonly string[] {
  return Object.keys(QUADS_CLASSIFICATION_BY_EXERCISE_ID).sort((a, b) => a.localeCompare(b));
}

export function listHamstringsClassificationExerciseIds(): readonly string[] {
  return Object.keys(HAMSTRINGS_CLASSIFICATION_BY_EXERCISE_ID).sort((a, b) => a.localeCompare(b));
}

export function listGlutesClassificationExerciseIds(): readonly string[] {
  return Object.keys(GLUTES_CLASSIFICATION_BY_EXERCISE_ID).sort((a, b) => a.localeCompare(b));
}

export function listCalvesClassificationExerciseIds(): readonly string[] {
  return Object.keys(CALVES_CLASSIFICATION_BY_EXERCISE_ID).sort((a, b) => a.localeCompare(b));
}
