/**
 * Back classification slice (v1).
 * One row per `EXERCISE_LIBRARY_V1` entry with `primaryBucket: "Back"`.
 */

import type { BackExerciseClassificationV1 } from "./classificationTypes";
import { CLASSIFICATION_SCHEMA_VERSION } from "./classificationTypes";

const PREFER_MUSCLE_CONTRIBUTION_MAP = new Set([
  "pull_up",
  "lat_pulldown",
  "barbell_row",
  "seated_cable_row",
  "romanian_deadlift",
]);

const J = {
  pull: ["shoulder", "elbow", "scapulothoracic"] as const,
  row: ["shoulder", "elbow", "scapulothoracic"] as const,
  hinge: ["spine", "hip", "shoulder"] as const,
  shrug: ["shoulder", "scapulothoracic"] as const,
  ext: ["spine", "hip"] as const,
  face: ["shoulder", "elbow", "scapulothoracic"] as const,
  mobFlex: ["spine", "hip"] as const,
  mobExt: ["spine", "shoulder"] as const,
  mobRot: ["spine", "shoulder"] as const,
  mobScap: ["scapulothoracic", "shoulder"] as const,
  isoSpine: ["spine", "hip"] as const,
  isoVert: ["shoulder", "elbow", "scapulothoracic"] as const,
  rope: ["shoulder", "elbow", "scapulothoracic"] as const,
  raise: ["shoulder", "scapulothoracic"] as const,
};

function backRow(
  exerciseId: string,
  row: Omit<
    BackExerciseClassificationV1,
    "schemaVersion" | "categoryKey" | "primaryMuscleGroup" | "preferExistingMuscleContributionMap"
  >,
): [string, BackExerciseClassificationV1] {
  return [
    exerciseId,
    {
      schemaVersion: CLASSIFICATION_SCHEMA_VERSION,
      categoryKey: "back",
      primaryMuscleGroup: "back",
      preferExistingMuscleContributionMap: PREFER_MUSCLE_CONTRIBUTION_MAP.has(exerciseId),
      ...row,
    },
  ];
}

function bulk(
  ids: readonly string[],
  row: Omit<
    BackExerciseClassificationV1,
    "schemaVersion" | "categoryKey" | "primaryMuscleGroup" | "preferExistingMuscleContributionMap" | "notes"
  > & { notes?: string },
): [string, BackExerciseClassificationV1][] {
  return ids.map((id) => backRow(id, row));
}

const ENTRIES: [string, BackExerciseClassificationV1][] = [
  ...bulk(
    [
      "pull_up",
      "chin_up",
      "neutral_grip_pull_up",
      "wide_grip_pull_up",
      "commando_pull_up",
      "typewriter_pull_up",
    ],
    {
      evidenceLevel: "library_derived",
      primaryPattern: "pull_vertical",
      laterality: "bilateral",
      loadModality: "bodyweight",
      compoundIsolation: "compound",
      plane: "vertical",
      jointsPrimary: J.pull,
      notes: "Chin-up adds biceps line vs pronated pull-up; both remain pull_vertical.",
    },
  ),
  ...bulk(["ring_pull_up"], {
    evidenceLevel: "library_derived",
    primaryPattern: "pull_vertical",
    laterality: "bilateral",
    loadModality: "bodyweight_rings",
    compoundIsolation: "compound",
    plane: "vertical",
    jointsPrimary: J.pull,
  }),
  ...bulk(["australian_pull_up"], {
    evidenceLevel: "library_derived",
    primaryPattern: "pull_horizontal_row",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "compound",
    plane: "horizontal",
    jointsPrimary: J.row,
  }),
  ...bulk(["archer_row"], {
    evidenceLevel: "library_derived",
    primaryPattern: "pull_horizontal_row",
    laterality: "unilateral_each_side",
    loadModality: "bodyweight",
    compoundIsolation: "compound",
    plane: "horizontal",
    jointsPrimary: J.row,
  }),
  ...bulk(["cable_pulldown", "cable_pulldown_close", "cable_pulldown_wide"], {
    evidenceLevel: "library_derived",
    primaryPattern: "pull_vertical",
    laterality: "bilateral",
    loadModality: "cable",
    compoundIsolation: "compound",
    plane: "vertical",
    jointsPrimary: J.pull,
  }),
  ...bulk(["lat_pulldown", "machine_pulldown"], {
    evidenceLevel: "library_derived",
    primaryPattern: "pull_vertical",
    laterality: "bilateral",
    loadModality: "machine_selectorized",
    compoundIsolation: "compound",
    plane: "vertical",
    jointsPrimary: J.pull,
  }),
  ...bulk(["band_lat_pulldown"], {
    evidenceLevel: "library_derived",
    primaryPattern: "pull_vertical",
    laterality: "bilateral",
    loadModality: "band",
    compoundIsolation: "compound",
    plane: "vertical",
    jointsPrimary: J.pull,
  }),
  ...bulk(["barbell_row", "pendlay_row", "yates_row", "landmine_row"], {
    evidenceLevel: "library_derived",
    primaryPattern: "pull_horizontal_row",
    laterality: "bilateral",
    loadModality: "barbell",
    compoundIsolation: "compound",
    plane: "horizontal",
    jointsPrimary: J.row,
  }),
  ...bulk(["barbell_rear_delt_row"], {
    evidenceLevel: "library_derived",
    primaryPattern: "scapular_isolation_raise",
    laterality: "bilateral",
    loadModality: "barbell",
    compoundIsolation: "isolation",
    plane: "horizontal",
    jointsPrimary: J.raise,
    notes: "Library buckets as Back with rear-delt emphasis; overlaps shoulder intelligence later.",
  }),
  ...bulk(["barbell_reverse_grip_incline_row"], {
    evidenceLevel: "library_derived",
    primaryPattern: "pull_horizontal_row",
    laterality: "bilateral",
    loadModality: "barbell",
    compoundIsolation: "compound",
    plane: "horizontal",
    jointsPrimary: J.row,
  }),
  ...bulk(["dumbbell_row", "dumbbell_chest_supported_row", "dumbbell_incline_row"], {
    evidenceLevel: "library_derived",
    primaryPattern: "pull_horizontal_row",
    laterality: "bilateral",
    loadModality: "dumbbell",
    compoundIsolation: "compound",
    plane: "horizontal",
    jointsPrimary: J.row,
  }),
  ...bulk(["single_arm_dumbbell_row"], {
    evidenceLevel: "library_derived",
    primaryPattern: "pull_horizontal_row",
    laterality: "unilateral_each_side",
    loadModality: "dumbbell",
    compoundIsolation: "compound",
    plane: "horizontal",
    jointsPrimary: J.row,
  }),
  ...bulk(["cable_row_straight_bar"], {
    evidenceLevel: "library_derived",
    primaryPattern: "pull_horizontal_row",
    laterality: "bilateral",
    loadModality: "cable",
    compoundIsolation: "compound",
    plane: "horizontal",
    jointsPrimary: J.row,
  }),
  ...bulk(["cable_one_arm_row"], {
    evidenceLevel: "library_derived",
    primaryPattern: "pull_horizontal_row",
    laterality: "unilateral_each_side",
    loadModality: "cable",
    compoundIsolation: "compound",
    plane: "horizontal",
    jointsPrimary: J.row,
  }),
  ...bulk(["machine_row", "smith_machine_row", "seated_cable_row"], {
    evidenceLevel: "library_derived",
    primaryPattern: "pull_horizontal_row",
    laterality: "bilateral",
    loadModality: "machine_selectorized",
    compoundIsolation: "compound",
    plane: "horizontal",
    jointsPrimary: J.row,
  }),
  ...bulk(["kettlebell_row"], {
    evidenceLevel: "library_derived",
    primaryPattern: "pull_horizontal_row",
    laterality: "bilateral",
    loadModality: "kettlebell",
    compoundIsolation: "compound",
    plane: "horizontal",
    jointsPrimary: J.row,
  }),
  ...bulk(["band_row", "band_seated_row", "band_bent_over_row", "band_high_row"], {
    evidenceLevel: "library_derived",
    primaryPattern: "pull_horizontal_row",
    laterality: "bilateral",
    loadModality: "band",
    compoundIsolation: "compound",
    plane: "horizontal",
    jointsPrimary: J.row,
  }),
  ...bulk(["ring_row"], {
    evidenceLevel: "library_derived",
    primaryPattern: "pull_horizontal_row",
    laterality: "bilateral",
    loadModality: "bodyweight_rings",
    compoundIsolation: "compound",
    plane: "horizontal",
    jointsPrimary: J.row,
  }),
  ...bulk(["inverted_row"], {
    evidenceLevel: "library_derived",
    primaryPattern: "pull_horizontal_row",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "compound",
    plane: "horizontal",
    jointsPrimary: J.row,
  }),
  ...bulk(["barbell_shrug", "trap_bar_shrug"], {
    evidenceLevel: "library_derived",
    primaryPattern: "shrug_vertical",
    laterality: "bilateral",
    loadModality: "barbell",
    compoundIsolation: "isolation",
    plane: "vertical",
    jointsPrimary: J.shrug,
  }),
  ...bulk(["dumbbell_shrug"], {
    evidenceLevel: "library_derived",
    primaryPattern: "shrug_vertical",
    laterality: "bilateral",
    loadModality: "dumbbell",
    compoundIsolation: "isolation",
    plane: "vertical",
    jointsPrimary: J.shrug,
  }),
  ...bulk(["cable_shrug"], {
    evidenceLevel: "library_derived",
    primaryPattern: "shrug_vertical",
    laterality: "bilateral",
    loadModality: "cable",
    compoundIsolation: "isolation",
    plane: "vertical",
    jointsPrimary: J.shrug,
  }),
  ...bulk(["band_shrug"], {
    evidenceLevel: "library_derived",
    primaryPattern: "shrug_vertical",
    laterality: "bilateral",
    loadModality: "band",
    compoundIsolation: "isolation",
    plane: "vertical",
    jointsPrimary: J.shrug,
  }),
  ...bulk(
    [
      "deadlift",
      "romanian_deadlift",
      "sumo_deadlift",
      "deficit_deadlift",
      "stiff_leg_deadlift",
      "snatch_grip_deadlift",
      "rack_pull",
      "good_morning",
      "trap_bar_deadlift",
      "seated_good_morning",
    ],
    {
      evidenceLevel: "library_derived",
      primaryPattern: "hip_hinge_pull",
      laterality: "bilateral",
      loadModality: "barbell",
      compoundIsolation: "compound",
      plane: "sagittal_hinge",
      jointsPrimary: J.hinge,
      notes: "Hip hinge family stresses spine + hip extensors; hamstrings vary by variant (library detailed tags).",
    },
  ),
  ...bulk(["jefferson_curl"], {
    evidenceLevel: "library_derived",
    primaryPattern: "mobility_segmental_spine",
    laterality: "bilateral",
    loadModality: "barbell",
    compoundIsolation: "isolation",
    plane: "sagittal_hinge",
    jointsPrimary: J.hinge,
    notes: "Library movement hinge + mobility; controlled spinal flexion emphasis.",
  }),
  ...bulk(["dumbbell_romanian_deadlift", "dumbbell_stiff_leg_deadlift", "dumbbell_deadlift"], {
    evidenceLevel: "library_derived",
    primaryPattern: "hip_hinge_pull",
    laterality: "bilateral",
    loadModality: "dumbbell",
    compoundIsolation: "compound",
    plane: "sagittal_hinge",
    jointsPrimary: J.hinge,
  }),
  ...bulk(["suitcase_deadlift"], {
    evidenceLevel: "library_derived",
    primaryPattern: "hip_hinge_pull",
    laterality: "unilateral_each_side",
    loadModality: "dumbbell",
    compoundIsolation: "compound",
    plane: "sagittal_hinge",
    jointsPrimary: J.hinge,
  }),
  ...bulk(["kettlebell_deadlift", "kettlebell_romanian_deadlift"], {
    evidenceLevel: "library_derived",
    primaryPattern: "hip_hinge_pull",
    laterality: "bilateral",
    loadModality: "kettlebell",
    compoundIsolation: "compound",
    plane: "sagittal_hinge",
    jointsPrimary: J.hinge,
  }),
  ...bulk(["band_deadlift", "banded_deadlift", "band_romanian_deadlift"], {
    evidenceLevel: "library_derived",
    primaryPattern: "hip_hinge_pull",
    laterality: "bilateral",
    loadModality: "band",
    compoundIsolation: "compound",
    plane: "sagittal_hinge",
    jointsPrimary: J.hinge,
  }),
  ...bulk(["smith_machine_deadlift"], {
    evidenceLevel: "library_derived",
    primaryPattern: "hip_hinge_pull",
    laterality: "bilateral",
    loadModality: "machine_smith",
    compoundIsolation: "compound",
    plane: "sagittal_hinge",
    jointsPrimary: J.hinge,
  }),
  ...bulk(["good_morning_bodyweight"], {
    evidenceLevel: "library_derived",
    primaryPattern: "hip_hinge_pull",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "compound",
    plane: "sagittal_hinge",
    jointsPrimary: J.hinge,
  }),
  ...bulk(["single_leg_rdl_bodyweight"], {
    evidenceLevel: "library_derived",
    primaryPattern: "hip_hinge_pull",
    laterality: "unilateral_each_side",
    loadModality: "bodyweight",
    compoundIsolation: "compound",
    plane: "sagittal_hinge",
    jointsPrimary: J.hinge,
  }),
  ...bulk(["machine_back_extension", "back_extension_45"], {
    evidenceLevel: "library_derived",
    primaryPattern: "hip_extension_spinal",
    laterality: "bilateral",
    loadModality: "machine_selectorized",
    compoundIsolation: "compound",
    plane: "sagittal_hinge",
    jointsPrimary: J.ext,
  }),
  ...bulk(["reverse_hyperextension", "reverse_hypers"], {
    evidenceLevel: "library_derived",
    primaryPattern: "hip_extension_spinal",
    laterality: "bilateral",
    loadModality: "machine_selectorized",
    compoundIsolation: "compound",
    plane: "sagittal_hinge",
    jointsPrimary: J.ext,
    notes: "Glute/hamstring line is significant; library still uses Back primary bucket.",
  }),
  ...bulk(["cable_face_pull"], {
    evidenceLevel: "library_derived",
    primaryPattern: "face_pull_external_rotation",
    laterality: "bilateral",
    loadModality: "cable",
    compoundIsolation: "compound",
    plane: "horizontal",
    jointsPrimary: J.face,
  }),
  ...bulk(["face_pull"], {
    evidenceLevel: "library_derived",
    primaryPattern: "face_pull_external_rotation",
    laterality: "bilateral",
    loadModality: "machine_selectorized",
    compoundIsolation: "compound",
    plane: "horizontal",
    jointsPrimary: J.face,
  }),
  ...bulk(["band_face_pull"], {
    evidenceLevel: "library_derived",
    primaryPattern: "face_pull_external_rotation",
    laterality: "bilateral",
    loadModality: "band",
    compoundIsolation: "compound",
    plane: "horizontal",
    jointsPrimary: J.face,
  }),
  ...bulk(["ring_face_pull"], {
    evidenceLevel: "library_derived",
    primaryPattern: "face_pull_external_rotation",
    laterality: "bilateral",
    loadModality: "bodyweight_rings",
    compoundIsolation: "compound",
    plane: "horizontal",
    jointsPrimary: J.face,
  }),
  ...bulk(["band_pull_apart"], {
    evidenceLevel: "library_derived",
    primaryPattern: "scapular_retraction_horizontal",
    laterality: "bilateral",
    loadModality: "band",
    compoundIsolation: "isolation",
    plane: "horizontal",
    jointsPrimary: J.raise,
  }),
  ...bulk(["band_w_raise", "band_y_raise", "band_t_raise"], {
    evidenceLevel: "library_derived",
    primaryPattern: "scapular_isolation_raise",
    laterality: "bilateral",
    loadModality: "band",
    compoundIsolation: "isolation",
    plane: "horizontal",
    jointsPrimary: J.raise,
  }),
  ...bulk(["dumbbell_w_raise", "dumbbell_y_raise", "dumbbell_t_raise"], {
    evidenceLevel: "library_derived",
    primaryPattern: "scapular_isolation_raise",
    laterality: "bilateral",
    loadModality: "dumbbell",
    compoundIsolation: "isolation",
    plane: "horizontal",
    jointsPrimary: J.raise,
  }),
  ...bulk(["prone_y_raise", "prone_t_raise", "prone_i_raise"], {
    evidenceLevel: "library_derived",
    primaryPattern: "scapular_isolation_raise",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "isolation",
    plane: "horizontal",
    jointsPrimary: J.raise,
  }),
  ...bulk(["childs_pose", "yoga_child_pose", "lat_stretch", "neck_stretch", "seated_forward_fold"], {
    evidenceLevel: "library_derived",
    primaryPattern: "mobility_flexion",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "isolation",
    plane: "na",
    jointsPrimary: J.mobFlex,
  }),
  ...bulk(["cobra_stretch", "yoga_cobra", "puppy_stretch", "yoga_upward_dog"], {
    evidenceLevel: "library_derived",
    primaryPattern: "mobility_extension",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "isolation",
    plane: "na",
    jointsPrimary: J.mobExt,
  }),
  ...bulk(["thread_the_needle"], {
    evidenceLevel: "library_derived",
    primaryPattern: "mobility_rotation",
    laterality: "unilateral_each_side",
    loadModality: "bodyweight",
    compoundIsolation: "isolation",
    plane: "transverse",
    jointsPrimary: J.mobRot,
  }),
  ...bulk(["scapular_push_up", "wall_slide"], {
    evidenceLevel: "library_derived",
    primaryPattern: "scapular_stability_mobility",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "isolation",
    plane: "na",
    jointsPrimary: J.mobScap,
  }),
  ...bulk(["superman_hold", "arch_hold"], {
    evidenceLevel: "library_derived",
    primaryPattern: "isometric_hold_spinal",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "mixed",
    plane: "sagittal_hinge",
    jointsPrimary: J.isoSpine,
  }),
  ...bulk(["back_lever_hold", "front_lever_hold", "front_lever_raise"], {
    evidenceLevel: "library_derived",
    primaryPattern: "isometric_hold_vertical_pull",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "mixed",
    plane: "vertical",
    jointsPrimary: J.isoVert,
  }),
  ...bulk(["rope_climb", "rope_climb_legless"], {
    evidenceLevel: "library_derived",
    primaryPattern: "rope_climb_vertical",
    laterality: "bilateral",
    loadModality: "bodyweight",
    compoundIsolation: "compound",
    plane: "vertical",
    jointsPrimary: J.rope,
  }),
];

export const BACK_CLASSIFICATION_BY_EXERCISE_ID: Readonly<
  Record<string, BackExerciseClassificationV1>
> = Object.fromEntries(ENTRIES);

export function listBackClassificationExerciseIds(): readonly string[] {
  return Object.keys(BACK_CLASSIFICATION_BY_EXERCISE_ID).sort((a, b) => a.localeCompare(b));
}

