import {
  buildEnrichmentEntry,
  buildMediaProfile,
  DEFAULT_TEMPO,
  defaultCoaching,
  defaultSafety,
  PAUSE_TEMPO,
  standardKeyframes,
  sub,
} from "./enrichmentEntryFactory";
import type { ExerciseLibraryEnrichmentV1 } from "./types";

function benchPressEnrichment(): ExerciseLibraryEnrichmentV1 {
  return buildEnrichmentEntry({
    exerciseId: "bench_press",
    movementPattern: "horizontal-press",
    planeOfMotion: "transverse",
    bodyRegion: "upper-body",
    laterality: "bilateral",
    kineticChain: "closed-chain",
    primaryJointActions: ["Shoulder horizontal adduction", "Elbow extension"],
    setupPosition: "Athlete supine on flat bench, eyes under bar, feet planted, scapulae retracted.",
    startPosition: "Bar held motionless at top lockout above chest/shoulder line.",
    endPosition: "Bar returned to full top lockout — end of single rep.",
    rangeOfMotionDefinition:
      "Single rep from top lockout → controlled descent → brief pause with bar on lower chest/sternum → press to full lockout.",
    stabilityDemand: "medium",
    loadingPattern: "Axial load through shoulders, elbows, and wrists with leg drive.",
    skillComplexity: "intermediate",
    tempoDefaults: PAUSE_TEMPO,
    primaryTrainingUses: ["strength", "hypertrophy", "general-fitness"],
    bestRepRanges: ["3–6 strength", "6–12 hypertrophy", "8–15 general fitness"],
    loadingGuidance: "Progress load when bar path, pause, and wrist stack remain consistent.",
    fatigueCost: "high",
    technicalFailureRisk: "medium",
    suggestedBlockTypes: ["primary compound", "strength wave", "hypertrophy accumulation"],
    progressionStrategy: "Add load, then reps, then pause duration before advanced variations.",
    regressionStrategy: "Floor press, dumbbell bench, or tempo bench with reduced load.",
    jointStressTags: ["shoulder", "elbow", "wrist"],
    pairingSuggestions: ["Horizontal pull", "Vertical pull", "Triceps isolation"],
    avoidPairingWith: ["Heavy overhead press same session if shoulder fatigue is high"],
    coaching: defaultCoaching(
      ["Set shoulders down and back before unracking", "Feet planted with stable leg drive", "Grip evenly with wrists stacked"],
      ["Lower with control to lower chest/sternum", "Brief pause without bounce", "Press to full lockout"],
      ["Bouncing bar off chest", "Elbows flaring excessively", "Feet lifting off floor", "Second descent at finish"],
      ["Cue pause on chest", "Reset foot drive each rep", "Keep wrists stacked"],
      "A horizontal press teaching a single controlled rep with pause on chest and full lockout.",
      ["Setup and foot drive", "Bar path and pause", "Lockout finish without second rep"],
    ),
    safety: defaultSafety(["shoulder-sensitive", "wrist-sensitive", "high-load"], ["Shoulder pain under load", "Wrist discomfort"]),
    substitutions: {
      regressions: [
        sub("dumbbell_bench_press", "Reduced load and independent arm stability", "regression"),
        sub("floor_press", "Shortened ROM for shoulder-friendly pressing", "regression"),
        sub("push_up", "Bodyweight horizontal press regression", "regression"),
      ],
      progressions: [sub("close_grip_bench_press", "Greater triceps demand", "progression"), sub("incline_bench_press", "Incline emphasis", "progression")],
      lateralSubstitutions: [sub("dumbbell_bench_press", "Similar pattern with dumbbells", "lateral")],
      equipmentSubstitutions: [sub("dumbbell_bench_press", "Dumbbell instead of barbell", "equipment")],
    },
    media: buildMediaProfile({
      keyframeRequirements: standardKeyframes([
        { poseId: "setup", poseLabel: "Setup", poseRole: "setup", sortOrder: 1, coachingCaption: "Setup: shoulders down and back, feet planted.", acceptanceCriteria: ["Full bench, barbell, plates, and feet visible in 16:9"] },
        { poseId: "start_lockout", poseLabel: "Start Lockout", poseRole: "start", sortOrder: 2, coachingCaption: "Start lockout: bar motionless above chest.", acceptanceCriteria: ["Wrists stacked", "Shoulder blades retracted"] },
        { poseId: "bottom_chest_pause", poseLabel: "Bottom Chest Pause", poseRole: "bottom", sortOrder: 3, coachingCaption: "Bottom pause: bar on lower chest/sternum.", acceptanceCriteria: ["Bar touches chest", "Brief pause — no bounce"], negativeCriteria: ["Bar hovering", "Bounce", "Second rep implied"] },
        { poseId: "finish_lockout", poseLabel: "Finish Lockout", poseRole: "finish", sortOrder: 4, coachingCaption: "Finish lockout: end of single rep.", acceptanceCriteria: ["Full lockout", "No second descent"], negativeCriteria: ["Watermark", "Logos", "Partial lockout"] },
      ]),
      imageQaFocus: ["Bar touches chest with pause", "Wrists stacked, feet planted", "Single rep only", "No watermark or logos"],
      futureVideoQaFocus: ["Single full rep", "No bounce", "No second rep at finish"],
    }),
    knownGaps: ["M9 keyframe spec exists — awaits expert review.", "M11 live image pack missing — no approved media."],
  });
}

function squatPattern(exerciseId: string, notes: string): ExerciseLibraryEnrichmentV1 {
  return buildEnrichmentEntry({
    exerciseId,
    movementPattern: "squat",
    planeOfMotion: "sagittal",
    bodyRegion: "lower-body",
    laterality: "bilateral",
    kineticChain: "closed-chain",
    primaryJointActions: ["Hip flexion/extension", "Knee flexion/extension"],
    setupPosition: "Stable stance with brace set.",
    startPosition: "Standing with hips and knees extended.",
    endPosition: "Returned to full standing lockout.",
    rangeOfMotionDefinition: "Descend to owned depth, drive to full lockout.",
    stabilityDemand: "high",
    loadingPattern: "Lower-body axial or machine-guided load.",
    skillComplexity: "intermediate",
    tempoDefaults: DEFAULT_TEMPO,
    primaryTrainingUses: ["strength", "hypertrophy"],
    bestRepRanges: ["5–8 strength", "8–12 hypertrophy"],
    loadingGuidance: "Own depth and brace before adding load.",
    fatigueCost: "high",
    technicalFailureRisk: "medium",
    suggestedBlockTypes: ["primary compound", "hypertrophy"],
    progressionStrategy: "Add load then volume.",
    regressionStrategy: "Reduce load or use machine variation.",
    jointStressTags: ["knee", "hip", "spine"],
    pairingSuggestions: ["Hinge pattern"],
    avoidPairingWith: ["Heavy hinge same session if fatigued"],
    coaching: defaultCoaching(
      ["Brace before descent", "Feet stable", "Break at hips and knees"],
      ["Knees track over toes", "Drive through mid-foot", "Full lockout"],
      ["Heels rising", "Knee cave", "Excessive forward lean"],
      ["Spread the floor", "Reduce load if depth breaks"],
      notes,
      ["Brace", "Depth", "Lockout"],
    ),
    safety: defaultSafety(["knee-sensitive", "low-back-sensitive", "spinal-loading"], ["Knee pain at depth"]),
    substitutions: {
      regressions: [sub("leg_press", "Machine squat regression", "regression")],
      progressions: [sub("front_squat", "Upright squat progression", "progression")],
      lateralSubstitutions: [sub("hack_squat", "Machine alternative", "lateral")],
      equipmentSubstitutions: [sub("leg_press", "Machine substitution", "equipment")],
    },
    media: buildMediaProfile({
      keyframeRequirements: standardKeyframes([
        { poseId: "setup", poseLabel: "Setup", poseRole: "setup", sortOrder: 1, coachingCaption: "Setup: brace and foot position.", acceptanceCriteria: ["Setup visible"] },
        { poseId: "start", poseLabel: "Start", poseRole: "start", sortOrder: 2, coachingCaption: "Start: standing lockout.", acceptanceCriteria: ["Full extension"] },
        { poseId: "bottom", poseLabel: "Bottom", poseRole: "bottom", sortOrder: 3, coachingCaption: "Bottom: owned depth.", acceptanceCriteria: ["Depth readable"] },
        { poseId: "finish", poseLabel: "Finish", poseRole: "finish", sortOrder: 4, coachingCaption: "Finish: drive to lockout.", acceptanceCriteria: ["Full lockout"] },
      ]),
    }),
  });
}

function hingePattern(exerciseId: string): ExerciseLibraryEnrichmentV1 {
  return buildEnrichmentEntry({
    exerciseId,
    movementPattern: "hinge",
    planeOfMotion: "sagittal",
    bodyRegion: "lower-body",
    laterality: "bilateral",
    kineticChain: "mixed",
    primaryJointActions: ["Hip flexion/extension"],
    setupPosition: "Hinge setup with neutral spine.",
    startPosition: "Standing lockout.",
    endPosition: "Returned to hip extension lockout.",
    rangeOfMotionDefinition: "Hip hinge through owned ROM, return to lockout.",
    stabilityDemand: "high",
    loadingPattern: "Hip-dominant load.",
    skillComplexity: "intermediate",
    tempoDefaults: DEFAULT_TEMPO,
    primaryTrainingUses: ["strength", "hypertrophy"],
    bestRepRanges: ["5–8 strength", "8–12 hypertrophy"],
    loadingGuidance: "Maintain neutral spine throughout.",
    fatigueCost: "high",
    technicalFailureRisk: "high",
    suggestedBlockTypes: ["posterior chain"],
    progressionStrategy: "Add load with consistent bar path.",
    regressionStrategy: "Reduce ROM or load.",
    jointStressTags: ["hip", "spine", "hamstring"],
    pairingSuggestions: ["Squat pattern"],
    avoidPairingWith: [],
    coaching: defaultCoaching(
      ["Hips back", "Bar close", "Brace set"],
      ["Neutral spine", "Drive hips forward", "Lockout glutes"],
      ["Rounded back", "Bar drifting forward"],
      ["Reduce load if spine changes"],
      "A hip-dominant hinge with neutral spine emphasis.",
      ["Hinge", "Bar path", "Lockout"],
    ),
    safety: defaultSafety(["low-back-sensitive", "spinal-loading", "high-load"], ["Low-back pain"]),
    substitutions: {
      regressions: [sub("romanian_deadlift", "Reduced ROM hinge", "regression")],
      progressions: [sub("sumo_deadlift", "Wide stance variation", "progression")],
      lateralSubstitutions: [],
      equipmentSubstitutions: [],
    },
    media: buildMediaProfile({
      keyframeRequirements: standardKeyframes([
        { poseId: "setup", poseLabel: "Setup", poseRole: "setup", sortOrder: 1, coachingCaption: "Setup: hinge ready.", acceptanceCriteria: ["Neutral spine"] },
        { poseId: "start", poseLabel: "Start", poseRole: "start", sortOrder: 2, coachingCaption: "Start: standing.", acceptanceCriteria: ["Lockout clear"] },
        { poseId: "bottom", poseLabel: "Bottom", poseRole: "bottom", sortOrder: 3, coachingCaption: "Bottom: hinge position.", acceptanceCriteria: ["Hinge visible"] },
        { poseId: "finish", poseLabel: "Finish", poseRole: "finish", sortOrder: 4, coachingCaption: "Finish: hip lockout.", acceptanceCriteria: ["Full extension"] },
      ]),
    }),
  });
}

function pressPattern(
  exerciseId: string,
  pattern: "horizontal-press" | "vertical-press",
  plane: "transverse" | "sagittal",
): ExerciseLibraryEnrichmentV1 {
  return buildEnrichmentEntry({
    exerciseId,
    movementPattern: pattern,
    planeOfMotion: plane,
    bodyRegion: "upper-body",
    laterality: "bilateral",
    kineticChain: "open-chain",
    primaryJointActions: pattern === "vertical-press" ? ["Shoulder flexion", "Elbow extension"] : ["Shoulder horizontal adduction", "Elbow extension"],
    setupPosition: "Stable base, shoulders set.",
    startPosition: "Arms at lockout start.",
    endPosition: "Returned to lockout.",
    rangeOfMotionDefinition: "Controlled press through full owned ROM.",
    stabilityDemand: "medium",
    loadingPattern: "Upper-body press load.",
    skillComplexity: "intermediate",
    tempoDefaults: DEFAULT_TEMPO,
    primaryTrainingUses: ["strength", "hypertrophy"],
    bestRepRanges: ["5–8 strength", "8–12 hypertrophy"],
    loadingGuidance: "Stable shoulders and wrists before adding load.",
    fatigueCost: "medium",
    technicalFailureRisk: "medium",
    suggestedBlockTypes: ["primary press"],
    progressionStrategy: "Add load then reps.",
    regressionStrategy: "Dumbbell or machine variation.",
    jointStressTags: ["shoulder", "elbow"],
    pairingSuggestions: ["Pulling pattern"],
    avoidPairingWith: [],
    coaching: defaultCoaching(
      ["Shoulders set", "Brace core"],
      ["Control descent", "Press to lockout"],
      ["Partial reps", "Shrugging"],
      ["Reduce load if form breaks"],
      "A pressing pattern with stable shoulders and full ROM.",
      ["Setup", "Press path", "Lockout"],
    ),
    safety: defaultSafety(pattern === "vertical-press" ? ["shoulder-sensitive", "overhead-position"] : ["shoulder-sensitive"], ["Shoulder pain"]),
    substitutions: {
      regressions: [sub("dumbbell_bench_press", "Dumbbell regression", "regression")],
      progressions: [],
      lateralSubstitutions: [],
      equipmentSubstitutions: [],
    },
    media: buildMediaProfile({
      keyframeRequirements: standardKeyframes([
        { poseId: "setup", poseLabel: "Setup", poseRole: "setup", sortOrder: 1, coachingCaption: "Setup position.", acceptanceCriteria: ["Setup visible"] },
        { poseId: "start", poseLabel: "Start", poseRole: "start", sortOrder: 2, coachingCaption: "Start lockout.", acceptanceCriteria: ["Lockout clear"] },
        { poseId: "bottom", poseLabel: "Bottom", poseRole: "bottom", sortOrder: 3, coachingCaption: "Bottom position.", acceptanceCriteria: ["Bottom readable"] },
        { poseId: "finish", poseLabel: "Finish", poseRole: "finish", sortOrder: 4, coachingCaption: "Finish lockout.", acceptanceCriteria: ["Full lockout"] },
      ]),
    }),
  });
}

function pullPattern(exerciseId: string, pattern: "horizontal-pull" | "vertical-pull"): ExerciseLibraryEnrichmentV1 {
  return buildEnrichmentEntry({
    exerciseId,
    movementPattern: pattern,
    planeOfMotion: pattern === "vertical-pull" ? "frontal" : "transverse",
    bodyRegion: "upper-body",
    laterality: "bilateral",
    kineticChain: "open-chain",
    primaryJointActions: ["Shoulder extension/adduction", "Elbow flexion"],
    setupPosition: "Scapulae set, torso stable.",
    startPosition: "Arms extended at start.",
    endPosition: "Returned to extension.",
    rangeOfMotionDefinition: "Pull through full ROM with scapular control.",
    stabilityDemand: "medium",
    loadingPattern: "Pulling load.",
    skillComplexity: "intermediate",
    tempoDefaults: DEFAULT_TEMPO,
    primaryTrainingUses: ["strength", "hypertrophy"],
    bestRepRanges: ["6–10 strength", "8–15 hypertrophy"],
    loadingGuidance: "Scapular control before load.",
    fatigueCost: "medium",
    technicalFailureRisk: "medium",
    suggestedBlockTypes: ["primary pull"],
    progressionStrategy: "Add load or reps.",
    regressionStrategy: "Assisted or machine variation.",
    jointStressTags: ["shoulder", "elbow"],
    pairingSuggestions: ["Pressing pattern"],
    avoidPairingWith: [],
    coaching: defaultCoaching(
      ["Shoulders down and back"],
      ["Pull with control", "Squeeze at contraction"],
      ["Momentum", "Incomplete ROM"],
      ["Reduce load if torso swings"],
      "A pulling pattern with scapular control.",
      ["Scapular setup", "Pull", "Return"],
    ),
    safety: defaultSafety(["shoulder-sensitive"], ["Shoulder pinching"]),
    substitutions: {
      regressions: [sub("lat_pulldown", "Assisted pull", "regression")],
      progressions: [sub("pull_up", "Bodyweight pull", "progression")],
      lateralSubstitutions: [sub("seated_cable_row", "Cable row alternative", "lateral")],
      equipmentSubstitutions: [],
    },
    media: buildMediaProfile({
      keyframeRequirements: standardKeyframes([
        { poseId: "setup", poseLabel: "Setup", poseRole: "setup", sortOrder: 1, coachingCaption: "Setup: scapulae set.", acceptanceCriteria: ["Setup visible"] },
        { poseId: "start", poseLabel: "Start", poseRole: "start", sortOrder: 2, coachingCaption: "Start: arms extended.", acceptanceCriteria: ["Start clear"] },
        { poseId: "top", poseLabel: "Peak", poseRole: "top", sortOrder: 3, coachingCaption: "Peak contraction.", acceptanceCriteria: ["Contraction readable"] },
        { poseId: "finish", poseLabel: "Finish", poseRole: "finish", sortOrder: 4, coachingCaption: "Controlled return.", acceptanceCriteria: ["Return under control"] },
      ]),
    }),
  });
}

function lungePattern(exerciseId: string): ExerciseLibraryEnrichmentV1 {
  return buildEnrichmentEntry({
    exerciseId,
    movementPattern: "lunge",
    planeOfMotion: "sagittal",
    bodyRegion: "lower-body",
    laterality: "unilateral",
    kineticChain: "closed-chain",
    primaryJointActions: ["Hip and knee flexion/extension"],
    setupPosition: "Split stance, torso tall.",
    startPosition: "Top of split stance.",
    endPosition: "Returned to start.",
    rangeOfMotionDefinition: "Descend to owned depth, drive back up.",
    stabilityDemand: "high",
    loadingPattern: "Unilateral lower-body load.",
    skillComplexity: "intermediate",
    tempoDefaults: DEFAULT_TEMPO,
    primaryTrainingUses: ["hypertrophy", "strength", "rehab-prehab"],
    bestRepRanges: ["8–12 per leg"],
    loadingGuidance: "Balance before load.",
    fatigueCost: "medium",
    technicalFailureRisk: "medium",
    suggestedBlockTypes: ["unilateral accessory"],
    progressionStrategy: "Add load then deficit.",
    regressionStrategy: "Reduce load or stride.",
    jointStressTags: ["knee", "hip"],
    pairingSuggestions: ["Bilateral leg work"],
    avoidPairingWith: [],
    coaching: defaultCoaching(
      ["Torso tall", "Front foot flat"],
      ["Drop straight down", "Drive through front heel"],
      ["Knee cave", "Torso collapse"],
      ["Reduce load if balance fails"],
      "A unilateral lunge with knee tracking and balance.",
      ["Stance", "Depth", "Drive"],
    ),
    safety: defaultSafety(["knee-sensitive", "balance-demand"], ["Knee pain in split"]),
    substitutions: {
      regressions: [sub("split_squat_dumbbell", "Static split regression", "regression")],
      progressions: [sub("bulgarian_split_squat_dumbbell", "Rear-foot elevated", "progression")],
      lateralSubstitutions: [sub("barbell_lunge", "Walking lunge", "lateral")],
      equipmentSubstitutions: [],
    },
    media: buildMediaProfile({
      keyframeRequirements: standardKeyframes([
        { poseId: "setup", poseLabel: "Setup", poseRole: "setup", sortOrder: 1, coachingCaption: "Split stance setup.", acceptanceCriteria: ["Stance visible"] },
        { poseId: "start", poseLabel: "Start", poseRole: "start", sortOrder: 2, coachingCaption: "Start position.", acceptanceCriteria: ["Stable start"] },
        { poseId: "bottom", poseLabel: "Bottom", poseRole: "bottom", sortOrder: 3, coachingCaption: "Bottom depth.", acceptanceCriteria: ["Depth readable"] },
        { poseId: "finish", poseLabel: "Finish", poseRole: "finish", sortOrder: 4, coachingCaption: "Return to start.", acceptanceCriteria: ["Controlled finish"] },
      ]),
    }),
  });
}

function isolationPattern(exerciseId: string, bodyRegion: string, joints: string[]): ExerciseLibraryEnrichmentV1 {
  return buildEnrichmentEntry({
    exerciseId,
    movementPattern: "isolation",
    planeOfMotion: "sagittal",
    bodyRegion,
    laterality: "bilateral",
    kineticChain: "open-chain",
    primaryJointActions: joints,
    setupPosition: "Joint aligned, torso stable.",
    startPosition: "Anatomical start position.",
    endPosition: "Return after peak contraction.",
    rangeOfMotionDefinition: "Full stretch to peak contraction without momentum.",
    stabilityDemand: "low",
    loadingPattern: "Single-joint isolation.",
    skillComplexity: "beginner",
    tempoDefaults: DEFAULT_TEMPO,
    primaryTrainingUses: ["hypertrophy", "rehab-prehab"],
    bestRepRanges: ["10–15", "12–20"],
    loadingGuidance: "Strict form over load.",
    fatigueCost: "low",
    technicalFailureRisk: "low",
    suggestedBlockTypes: ["isolation accessory"],
    progressionStrategy: "Add reps then load.",
    regressionStrategy: "Reduce load.",
    jointStressTags: [bodyRegion],
    pairingSuggestions: ["Compound for same region"],
    avoidPairingWith: [],
    coaching: defaultCoaching(
      ["Align joint"],
      ["Control both phases", "Squeeze at peak"],
      ["Swinging", "Partial ROM"],
      ["Reduce load for strict reps"],
      "An isolation exercise with strict ROM.",
      ["Alignment", "Contraction", "Return"],
    ),
    safety: defaultSafety([], ["Joint pinching"]),
    substitutions: { regressions: [], progressions: [], lateralSubstitutions: [], equipmentSubstitutions: [] },
    media: buildMediaProfile({
      keyframeRequirements: standardKeyframes([
        { poseId: "setup", poseLabel: "Setup", poseRole: "setup", sortOrder: 1, coachingCaption: "Setup aligned.", acceptanceCriteria: ["Setup visible"] },
        { poseId: "start", poseLabel: "Start", poseRole: "start", sortOrder: 2, coachingCaption: "Start position.", acceptanceCriteria: ["Start clear"] },
        { poseId: "top", poseLabel: "Peak", poseRole: "top", sortOrder: 3, coachingCaption: "Peak contraction.", acceptanceCriteria: ["Peak readable"] },
        { poseId: "finish", poseLabel: "Finish", poseRole: "finish", sortOrder: 4, coachingCaption: "Return to start.", acceptanceCriteria: ["Controlled return"] },
      ]),
    }),
  });
}

function hipThrustEnrichment(): ExerciseLibraryEnrichmentV1 {
  return buildEnrichmentEntry({
    exerciseId: "hip_thrust",
    movementPattern: "hinge",
    planeOfMotion: "sagittal",
    bodyRegion: "lower-body",
    laterality: "bilateral",
    kineticChain: "closed-chain",
    primaryJointActions: ["Hip extension"],
    setupPosition: "Upper back on bench, feet planted.",
    startPosition: "Hips low, shins near vertical.",
    endPosition: "Full hip extension, ribs down.",
    rangeOfMotionDefinition: "Drive hips to extension, pause, return.",
    stabilityDemand: "medium",
    loadingPattern: "Glute-dominant horizontal load.",
    skillComplexity: "intermediate",
    tempoDefaults: PAUSE_TEMPO,
    primaryTrainingUses: ["hypertrophy", "strength"],
    bestRepRanges: ["8–12 hypertrophy"],
    loadingGuidance: "Pause without lumbar extension.",
    fatigueCost: "medium",
    technicalFailureRisk: "low",
    suggestedBlockTypes: ["glute emphasis"],
    progressionStrategy: "Add load then pause.",
    regressionStrategy: "Bodyweight glute bridge.",
    jointStressTags: ["hip"],
    pairingSuggestions: ["Hinge or squat"],
    avoidPairingWith: [],
    coaching: defaultCoaching(
      ["Ribs down", "Bar over hips"],
      ["Drive through heels", "Pause at top"],
      ["Lumbar hyperextension"],
      ["Cue ribs to pelvis"],
      "Glute thrust with full hip extension and rib control.",
      ["Setup", "Drive", "Pause"],
    ),
    safety: defaultSafety(["low-back-sensitive"], ["Low-back discomfort at lockout"]),
    substitutions: {
      regressions: [sub("bodyweight_glute_bridge", "Bodyweight bridge", "regression")],
      progressions: [],
      lateralSubstitutions: [],
      equipmentSubstitutions: [],
    },
    media: buildMediaProfile({
      keyframeRequirements: standardKeyframes([
        { poseId: "setup", poseLabel: "Setup", poseRole: "setup", sortOrder: 1, coachingCaption: "Setup on bench.", acceptanceCriteria: ["Bench and feet visible"] },
        { poseId: "start", poseLabel: "Start Bottom", poseRole: "start", sortOrder: 2, coachingCaption: "Hips low.", acceptanceCriteria: ["Bottom clear"] },
        { poseId: "top", poseLabel: "Top Lockout", poseRole: "top", sortOrder: 3, coachingCaption: "Full extension pause.", acceptanceCriteria: ["Extension without hyperextension"] },
        { poseId: "finish", poseLabel: "Finish", poseRole: "finish", sortOrder: 4, coachingCaption: "Controlled return.", acceptanceCriteria: ["Controlled descent"] },
      ]),
    }),
  });
}

/** Top 25 enrichment entries — ranks 1–25 from Top 50 Priority Plan. */
export const TOP25_EXERCISE_ENRICHMENT_ENTRIES: readonly ExerciseLibraryEnrichmentV1[] = [
  benchPressEnrichment(),
  squatPattern("squat", "Foundational back squat pattern."),
  hingePattern("deadlift"),
  pressPattern("overhead_press", "vertical-press", "sagittal"),
  pullPattern("barbell_row", "horizontal-pull"),
  pullPattern("pull_up", "vertical-pull"),
  hingePattern("romanian_deadlift"),
  hipThrustEnrichment(),
  pressPattern("incline_bench_press", "horizontal-press", "transverse"),
  pullPattern("lat_pulldown", "vertical-pull"),
  squatPattern("leg_press", "Machine-guided squat pattern."),
  pressPattern("dumbbell_bench_press", "horizontal-press", "transverse"),
  pullPattern("seated_cable_row", "horizontal-pull"),
  squatPattern("front_squat", "Upright torso squat variation."),
  pressPattern("push_up", "horizontal-press", "transverse"),
  pressPattern("dumbbell_shoulder_press", "vertical-press", "sagittal"),
  pullPattern("dumbbell_row", "horizontal-pull"),
  lungePattern("split_squat_dumbbell"),
  lungePattern("bulgarian_split_squat_dumbbell"),
  isolationPattern("leg_curl", "lower-body", ["Knee flexion"]),
  isolationPattern("leg_extension", "lower-body", ["Knee extension"]),
  isolationPattern("calf_raise", "lower-body", ["Ankle plantarflexion"]),
  isolationPattern("face_pull", "upper-body", ["Shoulder horizontal abduction", "Scapular retraction"]),
  isolationPattern("lateral_raise", "upper-body", ["Shoulder abduction"]),
  isolationPattern("rear_delt_fly", "upper-body", ["Shoulder horizontal abduction"]),
];
